### ISSUE TITLE
STS->MN: Broken links within generated MN adoc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#11]
From 44002:

`<<iso_std_iso_44001_ed-1_en_clause_F,ISO 44001:2017,annex=F>>` should be `<<iso_std_iso_44001_ed-1_en,annex=F>>`.

No colons are allowed inside MN adoc anchor references.

**Comment by Intelligent2013** [comment]
> One more non-clear situation (adoptions\bs-en-12973\30314082.xml): in the text there are references:
> 
> ```
> <std>
> 	<std-ref>EN 16271<?doi https://doi.org/10.3403/30242720U?>
> 	</std-ref>
> </std>
> ```
> 
> But `EN 16271` is present in both `Normative References` and `Bibliography`:
> 
> ```
> <sec id="sec_2" sec-type="norm-refs">
> 	<label>2</label>
> 	<title>Normative references</title>
> 	...
> 	<ref-list content-type="norm-refs">
> 		...
> 		<ref>
> 			<std>
> 				<std-ref>EN 16271<?doi https://doi.org/10.3403/30242720U?>
> 				</std-ref>, <title>Value management ...</title>
> 			</std>
> 		</ref>
> 	</ref-list>
> </sec>
> 		
> 		
> <ref-list content-type="bibl" id="sec_bibl">
> 	<title>Bibliography</title>
> 	...
> 	<ref content-type="standard" id="ref_4">
> 		<label>[2]</label>
> 		<std>
> 			<std-ref>EN 16271<?doi https://doi.org/10.3403/30242720U?>
> 			</std-ref>, <title>Value management - ...</title>
> 		</std>
> 	</ref>
> ```
> 


Warning added:
` WARNING: Repeated reference - ENа16271, Value management - Functional expression of the need and functional performance specification - Requirements for expressing and validating the need to be satisfied within the process of purchasing or obtaining a product`
