### ISSUE TITLE
STS->MN: 44002 anchors for 44001 alternating?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#12]
From @opoudjis :

> The doc is alternating between`iso_std_iso_44001_en` and `iso_std_iso_44001_ed-1_en` as anchors

**Comment by Intelligent2013** [comment]
Perhaps we can restore the information about URI (example `iso:std:iso:44001:ed-1:en`) from `bibitem/docidentifier[@type='URN']`.

For example, currently the conversion workflow looks so:
- source STS XML
```xml
<std std-id="iso:std:iso:44001:ed-1:en:clause:F" type="dated">
	<std-ref>ISO 44001:2017<?doi https://doi.org/10.3403/30353016?>
	</std-ref>, Annex F</std>
```
- adoc
```
<<iso_std_iso_44001_ed_1_en,annex=F>>
```
- metanorma xml:
```xml
<eref type="inline" bibitemid="iso_std_iso_44001_ed_1_en" citeas="ISO 44001:2017"><localityStack><locality type="annex"><referenceFrom>F</referenceFrom></locality></localityStack>ISO 44001:2017, Annex  F</eref>
. . .
<bibitem id="iso_std_iso_44001_ed_1_en" type="standard">
	...
	<docidentifier type="ISO">ISO 44001:2017</docidentifier>
	<docidentifier type="URN">URN urn:iso:std:iso:44001:stage-60.60:ed-1:en</docidentifier>
...
```
- if remove `URN urn:i` and `:stage-60.60` from `docidentifier [type="URN"]`, and add 'locality ', then put the value into STS output xml:
```xml
<std type="dated" std-id="iso:std:iso:44001:ed-1:en:clause:F">
	<std-ref>ISO 44001:2017</std-ref>, Annex F
	</std>
```
So std-id in round-trip xml looks identical to source sts xml.

But there are another cases when std-id can't be restored as simple:
1. reference to undated ISO 44001
```xml
<std std-id="iso:std:iso:44001:en" type="undated">
	<std-ref>ISO 44001<?doi https://doi.org/10.3403/30353016U?>
	</std-ref>
</std>
```
In the bibliography section there isn't item for this reference. (we can add `ISO 44001` to the bibliography section, but URN will be `URN urn:iso:std:iso:44001:stage-60.60:ed-1:en`, i.e. identical to ISO 44001:2017,  and we can't differentiate one from another).

adoc:
```adoc
<<hidden_bibitem_iso_std_iso_44001_en,ISO 44001>>
```

metanorma xml:
```adoc
<eref type="inline" bibitemid="hidden_bibitem_iso_std_iso_44001_en" citeas="ISO&#160;44001">ISO&#160;44001</eref>
```

Perhaps the STS std-id can be restored from `bibitemid="hidden_bibitem_iso_std_iso_44001_en"` by replacing `_` to `:`.
In this case, on STS-MN stage, we need to differentiate `:` and `-` in std-id (example: `iso:std:iso:10667:-1:en`). It can be done, by replacing `:` to `__`, `-` to `___`.

2. Reference to `ISO 10667‑1`:
Source STS XML:
```xml
<std std-id="iso:std:iso:10667:-1:en" type="undated">
	<std-ref>ISO 10667‑1<?doi https://doi.org/10.3403/BSISO10667?>
</std-ref></std>
```
In metanorma xml, URN has some another structure - `iso:std:iso:10667:-1:ed-2:en`, i.e. with `ed-2` additionally.
So the round-trip STS XML will be:
```xml
<std type="undated" std-id="iso:std:iso:10667:-1:ed-2:en">
   <std-ref>ISO 10667‑1</std-ref>
</std>
```
I.e. `iso:std:iso:10667:-1:en` (source STS XML) vs. `iso:std:iso:10667:-1:ed-2:en` (round-trip STS XML)

**Comment by ronaldtse** [comment]
I think Relaton and/or Metanorma should help handle ISO URNs. Relaton right now supports generating ISO URNs, but I'm not sure if it supports downloading information using ISO URNs. Ping @andrew2net ?

**Comment by andrew2net** [comment]
Relaton-ISO generates URN when fetching ISO documents. To fetch documents using URN we need to implement reverse conversion URN -> PubID.
We have defined [URN structure](https://github.com/relaton/relaton-iec/issues/22#issuecomment-687191326) for ISO/IEC documents, so I think it isn't a big deal.

**Comment by Intelligent2013** [comment]
mnconvert in mn->sts conversion puts these values into `@std-id`:
- urn, if exists, (usually for ISO references), example: `std-id="iso:std:iso:19011:ed-3:en"`
- docidentifier (for non-ISO references), example: `std-id="BS 8887-2:2009"`
- the value 'as is' in mn xml, if reference to Bibliography isn't exist, example: `std-id="BS_ISO_56002_2019"`.
