### ISSUE TITLE
Word docx to adoc conversion feature

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#144]
To do: add Word document (.docx format) to adoc conversion based on Word document's styles:
- 'Foreword Title'
- 'Foreword Text'
- 'std_docNumber'
- 'zzSTDTitle'
- 'Heading 1'
- 'Heading 2'
- 'TermNum'
- 'Term(s)'
- 'Example'
- 'Note'
- 'RefNorm'
- 'Source'
- etc.

**Comment by Intelligent2013** [comment]
document.xml (WordprocessingML) from docx should be preliminary cleaned for some deleted text, because it can't be converted into adoc and significantly increases complexity of the conversion:

Deleted text on the coverpage:
![image](https://user-images.githubusercontent.com/5559926/169689139-5a6670c3-5652-44b5-b5dc-462f841da126.png)

Deleted items in the Bibliography:
![image](https://user-images.githubusercontent.com/5559926/169689254-f780a146-1c76-4abc-8492-40a3fe3e632d.png)

Deleted 'obligation' for Annex:
![image](https://user-images.githubusercontent.com/5559926/169691051-d9a51107-d3d3-4267-9ec2-9d78aa52bba7.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 regarding the styles, perhaps you can work with @opoudjis for an authoritative list of these styles and the mapping for metanorma.org? That would make users' lives much easier too. Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse as I understood, Word docx to mn adoc converter should support two kind of styles:
- docx styles from metanorma gem, and
- docx styles from ISO template (i.e. word document created in Word directly by ISO)
- and mix of them

Right?

**Comment by ronaldtse** [comment]
@Intelligent2013 No, that's a misunderstanding.

There are only 2 types of styles:
1. ISO Simple Template styles.
2. ISO Edited DIS template styles.

Metanorma is supposed to generate both types of Word templates. If Metanorma creates content outside these styles, it's wrong.

There is no mix of styles. A document can either be in the ISO Simple Template, or in the ISO Edited DIS template.

**Comment by Intelligent2013** [comment]
**DRAFT** mapping table between docx styles (ISO Simple Template) and adoc:

| ISO Simple Template  | docx internal xml style | adoc | mnconvert support
| ------------- | ------------- | ------------- | ------------- |
ANNEX | ANNEX | |
Admonition | Admonition | |
AdmonitionTitle | AdmonitionTitle | |
AltTerm(s) | AltTerms | |
Annex Figure Title Char | AnnexFigureTitleChar | |
Annex Figure Title | AnnexFigureTitle | |
Annex Table Title Char | AnnexTableTitleChar | |
Annex Table Title | AnnexTableTitle | |
Annex Table TitleCxSpFirst | AnnexTableTitleCxSpFirst | |
Annex Table TitleCxSpLast | AnnexTableTitleCxSpLast | |
Annex Table TitleCxSpMiddle | AnnexTableTitleCxSpMiddle | |
Biblio Title | BiblioTitle | |
Biblio | Biblio | |
Code | Code | |
Definition Char | DefinitionChar | |
Definition | Definition | |
DeprecatedTerm(s) | DeprecatedTerms | |
Example Char| ExampleChar | |
Example | Example | |
Example | Example | |
Figure Title Char | FigureTitleChar | |
Figure Title | FigureTitle | |
Figure TitleCxSpFirst | FigureTitleCxSpFirst | |
Figure TitleCxSpLast | FigureTitleCxSpLast | |
Figure TitleCxSpMiddle | FigureTitleCxSpMiddle | |
Foreword Text Char | ForewordTextChar | |
Foreword Text | ForewordText | |
Foreword Title | ForewordTitle | |
Formula | Formula | |
Intro Title | IntroTitle | |
List Paragraph Char | Char2 | |
NormRef | NormRef | |
Note Char | NoteChar | |
Note | Note | |
Quote | Quote | |
QuoteAttribution | QuoteAttribution | |
RecommendationTitle | RecommendationTitle | |
Source Char | SourceChar | |
Source | Source | |
SourceTitle | SourceTitle | |
Sourcecode | Sourcecode | |
Table Grid | MsoTableGrid | |
Table ISO | MsoISOTable MsoISOTableBig | |
Table title Char | TabletitleChar | |
Table titleCxSpFirst | TabletitleCxSpFirst | |
Table titleCxSpLast | TabletitleCxSpLast | |
Table titleCxSpMiddle | TabletitleCxSpMiddle | |
TableFootnote | TableFootnote | |
Tabletitle | Tabletitle | |
Term(s) | Terms | |
TermNum | TermNum | |
TitlePageSubhead | TitlePageSubhead | |
boilerplate-address | boilerplate-address | |
boilerplate-copyright | boilerplate-copyright | |
boilerplate-name | boilerplate-name | |
content | content | |
coverpage | coverpage | |
coverpage-doc-identity | coverpage-doc-identity | |
coverpage-logo | coverpage-logo | |
coverpage-stage-block | coverpage-stage-block | |
coverpage-tc-name | coverpage-tc-name | |
coverpage-title | coverpage-title | |
coverpage-warning | coverpage-warning | |
coverpage_docnumber | coverpage_docnumber | |
coverpage_docstage | coverpage_docstage | |
coverpage_techcommittee | coverpage_techcommittee    | |
coverpage_warning | coverpage_warning | |
doctitle | doctitle | |
example_label | example_label | |
figdl | figdl | |
formula | formula | |
formula_dl | formula_dl | |
msotoctextspan | MsoTocTextSpan | |
note_label | note_label | |
pseudocode| pseudocode | |
table.dl | table.dl | |
tablefootnoteref | TableFootnoteRef | |
title | title | |
title-second | title-second | |
zzAddress | zzAddress | |
zzContents | zzContents | |
zzCopyright | zzCopyright | |
zzSTDTitle | zzSTDTitle zzSTDTitle1 zzSTDTitle2 | |
zzWarning | zzWarning | |
zzWarningHdr | zzWarningHdr | |

**Comment by ronaldtse** [comment]
@Intelligent2013 just wanted to remind you that there is the ISO Edited DIS style, which uses different styles from ISO Simple Template. @opoudjis has been generating the Edited DIS style for DIS/FDIS/Final ISO Word documents, which is now very close to completion.

**Comment by Intelligent2013** [comment]
Word:
![image](https://user-images.githubusercontent.com/5559926/170291527-eac8e78d-aa81-4d12-b8e8-f111cf35eafc.png)

Math in WordprocessingML:
```xml
<m:oMath>
	<m:r>
		<w:rPr>
			<w:rStyle w:val="stem"/>
			<w:lang w:eastAsia="en-US"/>
		</w:rPr>
		<m:t>w</m:t>
	</m:r>
	<m:r>
		<m:rPr>
			<m:sty m:val="p"/>
		</m:rPr>
		<w:rPr>
			<w:rStyle w:val="stem"/>
			<w:lang w:eastAsia="en-US"/>
		</w:rPr>
		<m:t>=</m:t>
	</m:r>
	<m:f>
		<m:fPr>
			<m:ctrlPr>
				<w:rPr>
					<w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
				</w:rPr>
			</m:ctrlPr>
		</m:fPr>
		<m:num>
			<m:sSub>
				<m:sSubPr>
					<m:ctrlPr>
						<w:rPr>
							<w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
						</w:rPr>
					</m:ctrlPr>
				</m:sSubPr>
				<m:e>
					<m:r>
						<w:rPr>
							<w:rStyle w:val="stem"/>
							<w:lang w:eastAsia="en-US"/>
						</w:rPr>
						<m:t>m</m:t>
					</m:r>
				</m:e>
				<m:sub>
					<m:r>
						<w:rPr>
							<w:rStyle w:val="stem"/>
							<w:lang w:eastAsia="en-US"/>
						</w:rPr>
						<m:t>D</m:t>
					</m:r>
				</m:sub>
			</m:sSub>
		</m:num>
		<m:den>
			<m:sSub>
				<m:sSubPr>
					<m:ctrlPr>
						<w:rPr>
							<w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
						</w:rPr>
					</m:ctrlPr>
				</m:sSubPr>
				<m:e>
					<m:r>
						<w:rPr>
							<w:rStyle w:val="stem"/>
							<w:lang w:eastAsia="en-US"/>
						</w:rPr>
						<m:t>m</m:t>
					</m:r>
				</m:e>
				<m:sub>
					<m:r>
						<w:rPr>
							<w:rStyle w:val="stem"/>
							<w:lang w:eastAsia="en-US"/>
						</w:rPr>
						<m:t>s</m:t>
					</m:r>
				</m:sub>
			</m:sSub>
		</m:den>
	</m:f>
	<m:r>
		<m:rPr>
			<m:sty m:val="p"/>
		</m:rPr>
		<w:rPr>
			<w:rStyle w:val="stem"/>
			<w:lang w:eastAsia="en-US"/>
		</w:rPr>
		<m:t xml:space="preserve"> </m:t>
	</m:r>
</m:oMath>
```

To do: add math xml to MathML or `stem:[ ... ]` conversion.

**Comment by Intelligent2013** [comment]
**DRAFT** mapping table between DIS docx styles (ISO Edited DIS Template) and adoc:

Note: styles missed in ISO Simple Template

| ISO Edited DIS Template  | docx internal xml style | adoc example | mnconvert support
| ------------- | ------------- | ------------- | ------------- |
AMEND Heading 1 Unnumbered | AMENDHeading1Unnumbered | | 
AMEND Terms Heading | AMENDTermsHeading | | 
Admitted Term | AdmittedTerm | | 
Base_Text | BaseText | | 
Biblio Description | BiblioDescription | | 
Biblio Entry | BiblioEntry | | 
Biblio Text | BiblioText | | 
Body Text Indent 21 | BodyTextIndent21 | | 
Body Text Indent 22 | BodyTextIndent22 | | 
Body Text Indent 31 | BodyTextIndent31 | | 
Body Text Indent 32 | BodyTextIndent32 | | 
Body Text \(-\) | BodyText- | | 
Body Text indent 1 \(-\) | BodyTextindent1- | | 
Body Text indent 1 | BodyTextindent1 | | 
Body Text indent 2 \(-\) | BodyTextindent2- | | 
Body Text indent 3 \(-\) | BodyTextindent3- | | 
Body Text indent 4 \(-\) | BodyTextindent4- | | 
Body Text indent 4 | BodyTextindent4 | | 
Body Text_Center | BodyTextCenter | | 
Box-begin | Box-begin | | 
Box-end | Box-end | | 
Box-title | Box-title | | 
Chinese | Chinese | | 
Code \(--\) | Code-- | | 
Code \(-\) | Code- | | 
Courier | Courier | | 
Cover Title_A1 | CoverTitleA1 | | 
Cover Title_A2 | CoverTitleA2 | | 
Cover Title_A3 | CoverTitleA3 | | 
Cover Title_B | CoverTitleB | | 
Dimension_100 | Dimension100 | | 
Dimension_50 | Dimension50 | | 
Dimension_75 | Dimension75 | | 
Example continued | Examplecontinued | | 
Example indent 2 continued | Exampleindent2continued | | 
Example indent 2 | Exampleindent2 | | 
Example indent continued | Exampleindentcontinued | | 
Example indent | Exampleindent | | 
Figure Graphic | FigureGraphic | | 
Figure Image | FigureImage | | 
Figure description | Figuredescription | | 
Figure example | Figureexample | | 
Figure note | Figurenote | | 
Figure subtitle | Figuresubtitle | | 
Figure title | Figuretitle | | 
Figure title | Figuretitle0 | | 
Formula description | Formuladescription | | 
Front Head | FrontHead | | 
ISOCode | ISOCode | |
ISOCode_bold | ISOCodebold | |
ISOCode_italic | ISOCodeitalic | |
Index Head | IndexHead | | 
Key Text | KeyText | | 
Key Title | KeyTitle | | 
List Continue 1 \(-\) | ListContinue1- | | 
List Continue 1 | ListContinue1 | | 
List Continue 2 \(-\) | ListContinue2- | | 
List Continue 3 \(-\) | ListContinue3- | | 
List Continue 4 \(-\) | ListContinue4- | | 
List Continue 5 \(-\) | ListContinue5- | | 
List Number 1 \(-\) | ListNumber1- | | 
List Number 1 | ListNumber1 | | 
List Number 2 \(-\) | ListNumber2- | | 
List Number 3 \(-\) | ListNumber3- | | 
List Number 4 \(-\) | ListNumber4- | | 
List Number 5 \(-\) | ListNumber5- | | 
Main Title 1 | MainTitle1 | | 
Main Title 2 | MainTitle2 | | 
Main Title 3 | MainTitle3 | | 
Note continued | Notecontinued | | 
Note indent 2 continued | Noteindent2continued | | 
Note indent 2 | Noteindent2 | | 
Note indent continued | Noteindentcontinued | | 
Note indent | Noteindent | | 
Note | Note0 | | 
Notice | Notice | | 
RefNorm | RefNorm | | 
Table Graphic | TableGraphic | | 
Table ISO | TableISO | |
Table body \(+\) | Tablebody0 | | 
Table body \(--\) | Tablebody-- | | 
Table body \(-\) | Tablebody- | | 
Table description | Tabledescription | | 
Table footer | Tablefooter | | 
Table header \(+\) | Tableheader0 | | 
Table header \(--\) | Tableheader-- | | 
Table header \(-\) | Tableheader- | | 
Table header | Tableheader | | 
Table title | Tabletitle | see above | +
Table title | Tabletitle0 | | 
addition | addition | | 
au_base | aubase | | 
au_collab | aucollab | | 
au_deg | audeg | | 
au_fname | aufname | | 
au_member | aumember | | 
au_prefix | auprefix | | 
au_role | aurole | | 
au_suffix | ausuffix | | 
au_surname | ausurname | | 
bib_alt-year | bibalt-year | | 
bib_article | bibarticle | | 
bib_base | bibbase | | 
bib_book | bibbook | | 
bib_chapterno | bibchapterno | | 
bib_chaptertitle | bibchaptertitle | | 
bib_comment | bibcomment | | 
bib_deg | bibdeg | | 
bib_doi | bibdoi | | 
bib_ed-etal | bibed-etal | | 
bib_ed-fname | bibed-fname | | 
bib_ed-organization | bibed-organization | | 
bib_ed-suffix | bibed-suffix | | 
bib_ed-surname | bibed-surname | | 
bib_editionno | bibeditionno | | 
bib_etal | bibetal | | 
bib_extlink | bibextlink | | 
bib_fname | bibfname | | 
bib_fpage | bibfpage | | 
bib_institution | bibinstitution | | 
bib_isbn | bibisbn | | 
bib_issue | bibissue | | 
bib_journal | bibjournal | | 
bib_location | biblocation | | 
bib_lpage | biblpage | | 
bib_medline | bibmedline | | 
bib_number | bibnumber | | 
bib_organization | biborganization | | 
bib_pagecount | bibpagecount | | 
bib_patent | bibpatent | | 
bib_publisher | bibpublisher | | 
bib_reportnum | bibreportnum | | 
bib_school | bibschool | | 
bib_series | bibseries | | 
bib_seriesno | bibseriesno | | 
bib_suffix | bibsuffix | | 
bib_suppl | bibsuppl | | 
bib_surname | bibsurname | | 
bib_trans | bibtrans | | 
bib_unpubl | bibunpubl | | 
bib_url | biburl | | 
bib_volume | bibvolume | | 
bib_year | bibyear | | 
boilerplate-address1 | boilerplate-address1 | |
boilerplate-name1 | boilerplate-name1 | |
cite_app | citeapp | | 
cite_base | citebase | | 
cite_bib | citebib | | 
cite_box | citebox | | 
cite_en | citeen | | 
cite_eq | citeeq | | 
cite_fig | citefig | | 
cite_fn | citefn | | 
cite_sec | citesec | | 
cite_section | citesection | | 
cite_tbl | citetbl | | 
cite_tfn | citetfn | | 
content1 | content1 | |
coverpage_docnumber | coverpagedocnumber | |
coverpage_docstage | coverpagedocstage | |
coverpage_techcommittee | coverpagetechcommittee | |
coverpage_warning | coverpagewarning | |
deletion | deletion | | 
dl | dl | | 
dl_no indent | dlnoindent | | 
figure | figure | |
figuretitle | FigureTitle | see above | +
p2 | p2 | | 
p3 | p3 | | 
p4 | p4 | | 
p5 | p5 | | 
p6 | p6 | | 
part | part | | 
partlabel | partlabel | | 
recommendationtitle | AdmonitionTitle | |
recommendationtitle | recommendationtitle
sourcecode1 | sourcecode1 | | 
sourcetitle | SourceTitle | |
std_base | stdbase | | 
std_docNumber | stddocNumber | | 
std_docPartNumber | stddocPartNumber | | 
std_docTitle | stddocTitle | | 
std_documentType | stddocumentType | | 
std_footnote | stdfootnote | | 
std_publisher | stdpublisher | | 
std_section | stdsection | | 
std_suppl | stdsuppl | | 
std_year | stdyear | | 
stem | stem | |
stem1 | stem1 | | 
tablefootnote | tablefootnote | |
title-second1 | title-second1 | |
title1 | title1 | |
title2 | title2 | | 
zzAddress | zzAddress | skip | + 
zzCover Char | zzCoverChar | | 
zzCover | zzCover | | 
zzcopyrighthdr | zzcopyrighthdr | |

**Comment by Intelligent2013** [comment]
Further tasks:
- [ ] review processing (process comment reference to comments.xml)
- [ ] process `_term_ (<<term>>)` as `term:[ ]`
- [ ] remove Annex clause numbers (example: `A.1 Principle`)
- [ ] process '4.2.1' inline clause number
- [ ] add clause's id from `w:bookmarkStart`
- [ ] convert Word math markup to adoc or mathml

**Comment by Intelligent2013** [comment]
Added conversion from Word math markup (OMML) to MathML and AsciiMath (for simple formulas like `r` or `a=b+c`).
