### ISSUE TITLE
Word docx to adoc conversion for 'ISO Simple Template'

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#149]
Continue https://github.com/metanorma/mnconvert/issues/144.

**DRAFT** mapping table between docx styles (ISO Simple Template) and adoc:

| ISO Simple Template  | docx internal xml style | using in metanorma-iso  | adoc example | mnconvert support
| ------------- | ------------- | ------------- | ------------- | ------------- |
ANNEX | ANNEX | + | `[[AnnexA]]`<br/>`[appendix,obligation=normative]`<br/>`== Determination of defects` | +
Admonition | Admonition | - | |
AdmonitionTitle | AdmonitionTitle | - | |
AltTerm(s) | AltTerms | + | `alt:[paddy rice]`<br/>`alt:[rough rice]` | +
Annex Figure Title Char | AnnexFigureTitleChar | - | |
Annex Figure Title | AnnexFigureTitle | + | `.Split-it-right sample divider` | +
Annex Table Title Char | AnnexTableTitleChar | - | |
Annex Table Title | AnnexTableTitle | + | `.Table title` | +
Annex Table TitleCxSpFirst | AnnexTableTitleCxSpFirst | - | |
Annex Table TitleCxSpLast | AnnexTableTitleCxSpLast | - | |
Annex Table TitleCxSpMiddle | AnnexTableTitleCxSpMiddle | - | |
Biblio Title | BiblioTitle | + | `[bibliography]`<br/>`== Bibliography` | +
Biblio | biblio | + | `* [[[ISO3696]]],...` | +
Code | Code | + |  `[source]`<br/>`--`<br/>` puts "Hello, world."`<br/>`--` | +
Definition Char | DefinitionChar | -  | |
Definition | Definition | + |  `domain:[rice]` <br/>`organic and inorganic components other than whole or broken kernels` | +
DeprecatedTerm(s) | DeprecatedTerms | + | " `deprecated:[cargo rice]` | +
Example Char| ExampleChar | - | |
Example | Example | + | `==== `<br/>`Example text`<br/>`====` | +
Figure Title Char | FigureTitleChar | - | |
Figure Title | FigureTitle | + | `.Split-it-right sample divider` | +
Figure TitleCxSpFirst | FigureTitleCxSpFirst | -  | |
Figure TitleCxSpLast | FigureTitleCxSpLast | - | |
Figure TitleCxSpMiddle | FigureTitleCxSpMiddle | - | |
Foreword Text Char | ForewordTextChar | -  | |
Foreword Text | ForewordText | + | `Text` | +
Foreword Title | ForewordTitle | + | `== Foreword` | +
Formula | Formula | + | `stem:[...]` | +
Heading 1 | Heading1 | + | `== Title` | +
Heading 2 | Heading2 | + | `=== Title` | +
Heading 3 | Heading3 | + | `==== Title` | +
Heading 4 | Heading4 | + | `===== Title` | +
Heading 5 | Heading5 | + | `====== Title` | +
Heading 6 | Heading6 | + | `[level=6]`<br/>`====== Title` | +
Heading 7 | Heading7 | + | `[level=7]`<br/>`====== Title` | +
Intro Title | IntroTitle | + | `== Introduction` | +
List Paragraph Char | Char2 | - | |
NormRef  | normref | + | `* [[[ISO712]]],...` | +
Note Char | NoteChar | - | |
Note | note | + | `NOTE: This category includes ...` | +
Quote | Quote | - | |
QuoteAttribution | quoteattribution  | + | `[quote, ISO, "ISO7301,clause=1"]` | +
RecommendationTitle | RecommendationTitle | - | |
Source Char | SourceChar | - | |
Source | Source | + | " `<<ISO_7301_2011,clause=3.1>>` | +
SourceTitle | SourceTitle | - | |
Sourcecode | Sourcecode | -| |
Table Grid | MsoTableGrid | - | |
Table ISO | MsoISOTable MsoISOTableBig | - | |
Table title Char | TabletitleChar | - | |
Table titleCxSpFirst | TabletitleCxSpFirst | - | |
Table titleCxSpLast | TabletitleCxSpLast | - | |
Table titleCxSpMiddle | TabletitleCxSpMiddle | - | |
TableFootnote | TableFootnote | - | |
Tabletitle | tabletitle | + | `.Table title` | +
Term(s) | Terms | + | `=== term's name` | +
TermNum | TermNum | + | skip | +
titlepagesubhead | TitlePageSubhead | - | |
TOC x | TOCx | + | skip | +
boilerplate-address | boilerplate-address | - | |
boilerplate-copyright | boilerplate-copyright | - | |
boilerplate-name | boilerplate-name | - | |
content | content | - | |
coverpage | coverpage | - | |
coverpage-doc-identity | coverpage-doc-identity | - | |
coverpage-logo | coverpage-logo | - | |
coverpage-stage-block | coverpage-stage-block | - | |
coverpage-tc-name | coverpage-tc-name | - | |
coverpage-title | coverpage-title | - | |
coverpage-warning | coverpage-warning | - | |
coverpage_docnumber | coverpage_docnumber | - | |
coverpage_docstage | coverpage_docstage | - | |
coverpage_techcommittee | coverpage_techcommittee | - | |
coverpage_warning | coverpage_warning | - | |
doctitle | doctitle | - | |
example_label | examplelabel | + | skip |
figdl | figdl | - | |
formula | formula | - | |
formula_dl | formula_dl | - | |
msotoctextspan | MsoTocTextSpan | - | |
note_label | note_label | - | |
pseudocode| pseudocode | - | |
table.dl | table.dl | - | |
tablefootnoteref | tablefootnoteref | + | skip | +
title | title | - | |
title-second | title-second | - | |
zzAddress | zzaddress | + | skip | +
zzContents | zzContents | + | skip | +
zzCopyright | zzCopyright | + | skip | +
zzSTDTitle | zzSTDTitle zzSTDTitle1 zzSTDTitle2 | + | skip |
zzwarning | zzWarning | + | skip | +
zzwarninghdr | zzWarningHdr | + | skip | +

**Comment by Intelligent2013** [comment]
Docx to adoc conversion available in mnconvert v1.19.0 https://github.com/metanorma/mnconvert/releases/tag/v1.19.0
Conversion gaps listed above.

**Comment by ronaldtse** [comment]
@Intelligent2013 can you help provide usage guidance in a new blog post with a sample ? Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse ok, will do.
