### ISSUE TITLE
Create mnconvert-ruby wrapper

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#16]
As titled.
mnconvert is a consolidated application for sts2mn + mn2sts. So mnconvert-ruby wrapper should be just a copy of sts2mn-ruby and mn2sts-ruby codes.

**Comment by ronaldtse** [comment]
This task is necessary for https://github.com/metanorma/metanorma-standoc/issues/492

**Comment by CAMOBAP** [comment]
Mostly done, but I have problems:

1.
For file https://raw.githubusercontent.com/metanorma/mn-samples-iso/gh-pages/documents/international-standard/rice-en.cd.xml
```
Input: XML (/Users/camobap/Developers/Projects/riboseinc/metanorma/mnconvert-ruby/spec/fixtures/rice-en.cd.mn.xml)
Output: XML (/var/folders/9_/plmb2sws0k1_8s29w7d6hqfh0000gn/T/d20210707-33295-853rni/rice-en.cd.sts.xml), format NISO STS

DocumentBuilderFactory implementation: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl loaded from: Java Runtime
XPathFactory implementation: org.apache.xpath.jaxp.XPathFactoryImpl loaded from: file:/Users/camobap/Developers/Projects/riboseinc/metanorma/mnconvert-ruby/bin/mnconvert.jar
TransformerFactory implementation: org.apache.xalan.processor.TransformerFactoryImpl loaded from: file:/Users/camobap/Developers/Projects/riboseinc/metanorma/mnconvert-ruby/bin/mnconvert.jar
SAXParserFactory implementation: com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl loaded from: Java Runtime

Transforming...
file:/Users/camobap/Developers/Projects/riboseinc/metanorma/mnconvert-ruby/spec/fixtures/rice-en.cd.mn.xml; Line #1; Column #1; Premature end of file.
Validate XML againts XSD NISO-STS-extended-1-MathML3-XSD/NISO-STS-extended-1-mathml3.xsd...
/var/folders/9_/plmb2sws0k1_8s29w7d6hqfh0000gn/T/d20210707-33295-853rni/rice-en.cd.sts.xml is NOT valid reason:
[ERROR] org.xml.sax.SAXParseException; systemId: file:/var/folders/9_/plmb2sws0k1_8s29w7d6hqfh0000gn/T/d20210707-33295-853rni/rice-en.cd.sts.xml; lineNumber: 1; columnNumber: 1; Premature end of file.
[ERROR] org.xml.sax.SAXParseException; systemId: file:/var/folders/9_/plmb2sws0k1_8s29w7d6hqfh0000gn/T/d20210707-33295-853rni/rice-en.cd.sts.xml; lineNumber: 1; columnNumber: 1; Premature end of file.
```

@Intelligent2013 maybe I use wrong/outdated XML samples?

**Comment by Intelligent2013** [comment]
Very strange. Source xml source is correct. I've tried to execute:
`java -jar mnconvert-1.8.0.jar rice-en.cd.xml`
and completed successfully:
```
Input: XML (D:\Metanorma\mnconvert.my\test01\rice-en.cd.xml)
Output: XML (D:\Metanorma\mnconvert.my\test01\rice-en.cd.sts.niso.xml), format NISO STS

Transforming...
Validate XML againts XSD NISO-STS-extended-1-MathML3-XSD\NISO-STS-extended-1-mathml3.xsd...
D:\Metanorma\mnconvert.my\test01\rice-en.cd.sts.niso.xml is valid.
End!
```

I don't like this message: `file:/Users/camobap/Developers/Projects/riboseinc/metanorma/mnconvert-ruby/spec/fixtures/rice-en.cd.mn.xml; Line #1; Column #1; Premature end of file.`
It means that something wrong with _input_ file. Source file is `rice-en.cd.mn.xml`, not `rice-en.cd.xml`. How did you generate it? Could you put it here?

**Comment by CAMOBAP** [comment]
@Intelligent2013 sorry for the false alarm I redownloaded the jar, and now it works correctly I didn't see such errors.

For now, the only test that is failing is https://github.com/metanorma/mnconvert-ruby/blob/main/spec/mnconvert_spec.rb#L32-L48 I think I see why this happens, fixing right now

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/mnconvert/pull/23 - auto releases enabled

**Comment by CAMOBAP** [comment]
Done
