### ISSUE TITLE
Adding new Intercharge DTD/XSD/RNG tags

### ISSUE THREAD

**Issue by bdziadosz96** [metanorma/mnconvert#162]
Hello, I'm trying to validate or convert NISO STS XML to MN and during that process 
[ERROR] Validation error: java.io.FileNotFoundException: /home/../mnconvert/NISO-STS-interchange-1-mathml2.dtd (File or catalog doesn't exist). It is connected to the norm that started with 
`<!DOCTYPE adoption
        PUBLIC "-//NISO//DTD NISO STS Interchange Tag Set (NISO STS) DTD with MathML 3.0 v0.2 20170331//EN" "NISO-STS-interchange-1-mathml3.dtd">`

If needed then specific norm could by attached in this thread.

Thank You

**Comment by Intelligent2013** [comment]
> If needed then specific norm could by attached in this thread.

@bdziadosz96 yes, please attach it.

**Comment by bdziadosz96** [comment]
[wrappedform.txt](https://github.com/metanorma/mnconvert/files/9157577/wrappedform.txt)
Cannot attach .xml so I wrapped it into txt

**Comment by ronaldtse** [comment]
@bdziadosz96 thanks for the sample. I noticed that in the original post it had a different DOCTYPE:

```xml
<!DOCTYPE adoption PUBLIC "-//NISO//DTD NISO STS Interchange Tag Set (NISO STS) DTD
   with MathML 3.0 v0.2 20170331//EN" "NISO-STS-interchange-1-mathml3.dtd">
```

```xml
<!DOCTYPE standard PUBLIC "-//NISO//DTD NISO STS Interchange Tag Set (NISO STS) DTD 
  with MathML 2.0 v1.0 20171031//EN" "NISO-STS-interchange-1-mathml2.dtd">
```

We currently only support the "Extended Tag Set" not the "Interchange Tag Set", though it might not be a stretch to also support that...

**Comment by bdziadosz96** [comment]
Okay, thanks i really appreciate that, so basically You propose a date on which new tags will be covered when it comes to intercharge?

**Comment by ronaldtse** [comment]
@Intelligent2013 is currently investigating how mnconvert can handle the Interchange STS format. The only difference is to drop complex table support, but we have to assess how to handle the conversion between complex tables in Metanorma XML into STS interchange, because at authoring time we do not know what format the document will get exported as.

It would certainly help to know of your exact use case to better support here.

e.g. is the use case to convert NSB standards that are NSB-EN-ISO adoptions into Metanorma for editing/republication? Or is this an EN / ISO data feed that gets converted?

**Comment by Intelligent2013** [comment]
Currently added (https://github.com/metanorma/mnconvert/pull/166):
- checking against Interchange tag set (by default, `--tagset` command line parameter)
- checking against MathML3 (default) and MathML2 (`--mathml` command line parameter)

Further tasks:
- ignore DTD reference in the XML header and check against DTD/XSD selected by command line parameters (I have to add ResourceResolver to XSD Validator class to ignore DTD in the header)
- or check against DTD/XSD from XML header if it exists inside jar file

**Comment by Intelligent2013** [comment]
@bdziadosz96 could you check mnconvert version in https://github.com/metanorma/mnconvert/pull/166 for your purposes?

The command:
```
java -jar mnconvert-1.19.0.jar wrappedform.xml  --check-type xsd-niso
```
validates xml against xml against 'default' 'NISO-STS-interchange-1-MathML3-XSD\NISO-STS-interchange-1-mathml3.xsd'

You can specify interchange or extended tag set by the parameter `--tagset extended` and MathML version 2 or 3 by the parameter `--mathml 2`:

```
java -jar mnconvert-1.19.0.jar wrappedform.xml  --check-type dtd-niso --tagset extended --mathml 2
```
(Validate XML against DTD NISO-STS-extended-1-MathML2-DTD\NISO-STS-extended-1-mathml2.dtd)

Similar parameter for the conversion mode.

**Comment by bdziadosz96** [comment]
Hello, I checked it and here is my following question.
1) Validation passing for both types of format when xml is tagged as a MathML2. Shouldn't be invalidate when we are checking MathML3 with --tag extended --math ml2?

2)Conversion mode is not working for this xml, I've got NPE 
`Transforming...
java.lang.NullPointerException
        at java.base/sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.metanorma.STS2MN_XsltConverter.convertsts2mn(STS2MN_XsltConverter.java:223)
        at org.metanorma.STS2MN_XsltConverter.process(STS2MN_XsltConverter.java:134)
        at org.metanorma.mnconvert.main(mnconvert.java:396)
`

**Comment by Intelligent2013** [comment]
> 1. Validation passing for both types of format when xml is tagged as a MathML2. Shouldn't be invalidate when we are checking MathML3 with --tag extended --math ml2?

@bdziadosz96 if xml doesn't contain MathML3 specific tags, then xml will be valid ok with MathML2 too.

> 2)Conversion mode is not working for this xml, I've got NPE

- please specify the command line
- what is OS?
- what is java version?

**Comment by bdziadosz96** [comment]
@Intelligent2013 

- 2) 
- java -jar target/mnconvert-1.19.0.jar iso_std_iso_12402-6_ed-2_v1_en.xml -o wrappedconverted.xml -of xml  
- Ubuntu22.04
- Java 11/17 on both failing

**Comment by Intelligent2013** [comment]
@bdziadosz96 issue fixed: https://github.com/metanorma/mnconvert/pull/166

**Comment by bdziadosz96** [comment]
I'am still facing this problem, after rebuild project I've got java.io.FileNotFoundException: /home/../mnconvert/NISO-STS-interchange-1-mathml2.dtd (No such file or directory)
Unknown input file format ''

Can You copy exact command that allow to convert to xml?

Additionaly I want to ask about any other convertsion, in this case I've obtain NISO STS XML or METANORMA XML so any hints how to convert it to HTML? Main metanormy in R allows to obtain HTML/DOC/PDF from IEEE, so maybe any hints how I can deal with it?

**Comment by ronaldtse** [comment]
@Intelligent2013 will answer the first question about the command.

> Additionaly I want to ask about any other convertsion, in this case I've obtain NISO STS XML or METANORMA XML so any hints how to convert it to HTML? Main metanormy in R allows to obtain HTML/DOC/PDF from IEEE, so maybe any hints how I can deal with it?

Metanorma supports different "flavors" for SDOs/NSBs, with publicly available flavors described on www.metanorma.org.

If you have NISO STS XML that is in one of the supported flavors (e.g. ISO, IEC), it can be converted into Metanorma AsciiDoc format via `mnconvert`, which allows you to convert to HTML. 

If you are working with NISO STS XML from an SDO not supported by Metanorma, you could create your own Metanorma flavor, or contact us for commercial support.

**Comment by Intelligent2013** [comment]
@bdziadosz96 your commands almost correct, instead of `--mathml2` should be `--mathml 2`, but looks like it's just a typo.
In my environment:
```
java -jar target/mnconvert-1.19.0.jar wrapped.xml --check-type dtd-niso --tagset interchange --mathml 2
```
output:
```
mnconvert

Validate XML against DTD NISO-STS-interchange-1-MathML2-DTD\NISO-STS-interchange-1-mathml2.dtd...
D:\Metanorma\mnconvert.my\wrappedform.xml is valid.
```

and 
```
java -jar target/mnconvert-1.19.0.jar wrapped.xml -o wrappedconverted.xml -of xml
```
output:
```
mnconvert

Input: XML (wrappedform.xml)
Output: XML (wrappedconverted.xml)

Transforming...
End!
```

What is git branch did you choose? Please make sure that you are using the branch `dtd_xsd_update`, not `main`.

> Additionaly I want to ask about any other convertsion, in this case I've obtain NISO STS XML or METANORMA XML so any hints how to convert it to HTML?

mnconvert doesn't support html format as 'ready-to-use' output format, but you can developed own XSL module for conversion NISO XML into HTML format and specify it via command line parameter `-s` or `--xsl-file`. For instance, `html.xsl` looks so:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
					xmlns:mml="http://www.w3.org/1998/Math/MathML" 
					xmlns:tbx="urn:iso:std:iso:30042:ed-1" 
					xmlns:xlink="http://www.w3.org/1999/xlink" 
					xmlns:xalan="http://xml.apache.org/xalan" 
					xmlns:java="http://xml.apache.org/xalan/java" 
					xmlns:redirect="http://xml.apache.org/xalan/redirect"
					xmlns:metanorma-class-util="xalan://org.metanorma.utils.Util"
					exclude-result-prefixes="xalan mml tbx xlink java metanorma-class-util"
					extension-element-prefixes="redirect"
					version="1.0">
	<xsl:output version="1.0" method="html" encoding="UTF-8" indent="yes"/>

	<xsl:template match="/">
		<html>
			<body>
				<h1>Example</h1>
				<!-- call another templates -->
			</body>
		</html>
	</xsl:template>

</xsl:stylesheet>
```
Command line:
```
java -jar target/mnconvert-1.19.0.jar wrappedform.xml -o wrappedconverted.xml -of xml -s html.xsl
```
The resulted `wrappedconverted.xml` will contain:
```xml
<html>
<body>
<h1>Example</h1>
</body>
</html>
```

**Comment by bdziadosz96** [comment]
That's awesome, thank You very much. I will gather this information and try to test it into my application. Let's leave this thread open for few days please :)

**Comment by ronaldtse** [comment]
@bdziadosz96 just wanted to make sure that you were able to test the results. Feel free to open a new ticket if you need further help. Thanks!
