### ISSUE TITLE
ISO XML to MN: set term domain

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#186]
As in https://github.com/metanorma/iso-14812/commit/5b12670db201e1c6d229472a7c9c765a60a441be

In the ISO STS XML to MN conversion, we need to move the initial `<...>` content in the description into `domain:[...]` to set the domain.

**Comment by Intelligent2013** [comment]
Done. Issue fixed in https://github.com/metanorma/mnconvert/releases/tag/v1.21.0

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
