### ISSUE TITLE
ISO XML to MN: Do not generate boilerplate when there is no content

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#187]
In the ISO XML conversion from ISO 14812 to Metanorma AsciiDoc I'm seeing these sections generated, but they should not be included if there is no text.

<img width="1013" alt="Screen Shot 2022-08-25 at 2 09 04 PM" src="https://user-images.githubusercontent.com/11865/186588010-066a25c9-d92c-4eeb-b6b9-fcf8f0fed393.png">

**Comment by Intelligent2013** [comment]
Done in mnconvert v1.22.0 (https://github.com/metanorma/mnconvert/releases/tag/v1.22.0)
