### ISSUE TITLE
Regenerate id with ISO/IEC Guidelines

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#193]
Source: https://github.com/metanorma/mnconvert/issues/190

Regenerate id (and references) from Metanorma XML to NISO STS XML conversion for ISO and IEC documents.

For instance, for input Metanorma XML `<foreword id="foreword"...>`:
- ISO: `@id="sec_foreword"`
- IEC: `@id="sec-foreword"`

The full rules for IDs see in Annexes E and F in ISO/IEC Coding Guidelines.

**Comment by ronaldtse** [comment]
@Intelligent2013 after formatting according to the ISO/IEC Guidelines we should have a blog post to talk about the changes we had to make.

**Comment by Intelligent2013** [comment]
Table footnotes id:
- ISO
  - Formal tables: `table-fn_[table footnote sequence within the document]`
  - Informal tables: `table-fn_[id of the informal table].[fn sequence within the table]`
- IEC
  - `tfn-x-y` where "x" is the table number as coded in `<label>` and "y" is the sequential number of the footnote inside the table.

**Comment by Intelligent2013** [comment]
Numbered formulae:
- ISO: `id="formula_1"`
- IEC: `id="for-1"`

Unnumbered formulae:
- IEC: `id="for-informal-X-Y"`, where X is the number of the subclause and Y the sequential number of the unnumbered formula inside the subclause, for example: `<disp-formula id="for-informal-5.1.3-1">`

**Comment by Intelligent2013** [comment]
MathML:
`@id="mml_m[number]"`, where [number] representing the sequential position of the `<mml:math>` element in the document.

Example: `<mml:math id=”mml_m5”>`.

**Comment by Intelligent2013** [comment]
Terms and definitions:

- ISO
   - `term-sec` `@id="sec_..."`
   - `tbx:term-entry` `@id=“term_..."`
- IEC
   - `term-sec` `@id="con-..."`
   - `tbx:term-entry` `@id=“te-..."`
   - `tbx:term` `@id`="ter-...", corresponds to the term itself (example: `<tbx:term id="ter-sound_pressurep">sound pressure</tbx:term>`)

**Comment by Intelligent2013** [comment]
In the Guidelines there is a discrepancy for `Scope`:
- ISO `@id= "sec_scope"`
- IEC `@id= "sec-scope"`
but in the example below `@id="sec_1"`:
```xml
<sec id="sec_1" sec-type="scope">
  <label>1</label><title>Scope</title>
```
Currently, mnconvert generates `@id="sec_1"`.
