### ISSUE TITLE
ISO/IEC Coding Guidelines: general unit statements in tables 

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#224]
Source: https://github.com/metanorma/mnconvert/issues/190

From Guidelines:
> 6.6.5 General unit statements in tables
> When a table contains text describing the units used in the table it is captured as `<p>` with `@content-type=”dimension”` in `<table-wrap-foot>`.
> For example:
![image](https://user-images.githubusercontent.com/5559926/188876169-a0f33331-825a-4806-9cf1-cfb01da9af1f.png)
>is coded as:
```xml
</table>
<table-wrap-foot>
<p content-type="Dimension" specific-use="100">Mass fractions in per cent</p>
</table-wrap-foot>
</table-wrap>
```

Currently, Metanorma doesn't support it.

~It will be converted as table's note.~

**Comment by ronaldtse** [comment]
This needs to be supported by metanorma-standoc.

**Comment by Intelligent2013** [comment]
Done. Now, it converts to:
```adoc
[NOTE,type=units]
Mass fractions in per cent
```
