### ISSUE TITLE
ISO/IEC Coding Guidelines: Unit statements in figures

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#228]
Source: https://github.com/metanorma/mnconvert/issues/190

From `8.4`:
> When a figure contains a unit statement such as “Dimensions in millimetres”, this is coded as as `<p>` with `@content-type=”dimension”`.
> ![image](https://user-images.githubusercontent.com/5559926/194920150-ac09708e-214b-47e8-9384-abbdefefce31.png)

Currently, mnconvert process it as figure's note.

**Comment by ronaldtse** [comment]
This needs to be supported by metanorma-standoc, related to https://github.com/metanorma/mnconvert/issues/224

**Comment by Intelligent2013** [comment]
Done.
