### ISSUE TITLE
STS->MN adoc: change arguments order in  term:[] macros

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#27]
Source: https://github.com/metanorma/metanorma-bsi/issues/37

Change from
```adoc
term:[rendering,term]
```
to
```adoc
term:[term, rendering]
```

**Comment by ronaldtse** [comment]
@Intelligent2013 just wanted to let you know the preferred new syntax is:

```
{{term,rendering}}
```

instead of
```
term:[term,rendering]
```

Can you help update this? Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse  xslt updated.
