### ISSUE TITLE
Error: "rspec" from pngcheck conflicts with installed executable from seven-zip

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#287]
From https://github.com/metanorma/mnconvert/actions/runs/3243260908/jobs/5317714656:
```
Successfully installed asciimath2unitsml-0.4.3
Building native extensions. This could take a while...
ERROR:  Error installing metanorma-cli:
	"rspec" from pngcheck conflicts with installed executable from seven-zip
Successfully installed ox-2.14.11
```

The error occurs on Ubuntu and MacOs.
On Windows is ok.
4 hours ago everything was ok:
https://github.com/metanorma/mnconvert/actions/runs/3241667812/jobs/5313919769
```
...
Successfully installed asciimath2unitsml-0.4.3
Building native extensions. This could take a while...
Successfully installed ox-2.14.11
...
```

**Comment by ronaldtse** [comment]
This is a bug -- both pngcheck and seven-zip should not provide executables.

Ping @maxirmx for help.

**Comment by ronaldtse** [comment]
Two tasks:
* https://github.com/metanorma/pngcheck-ruby/issues/27
* https://github.com/fontist/seven_zip_ruby/issues/10

**Comment by Intelligent2013** [comment]
Confirm, fixed.
