### ISSUE TITLE
Fix styled-content parsing in XML-to-ADOC conversion

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mnconvert#291]
In relation to https://github.com/metanorma/iso-10303-detached-docs/issues/118

From ISO 10303 part 24:
```xml
<styled-content style="font-family:Courier,monospace">sdaiTRUE</styled-content>
```

`styled-content` tag with `font-family: Corier,monospace` should be encoded as monospace
text in Asciidoc output.

I.e.
```adoc
`sdaiTRUE`
```

**Comment by Intelligent2013** [comment]
There is a case when `styled-content` placed inside `preformat`:
```xml
<preformat orientation="portrait" position="float" preformat-type="code" xml:space="preserve"><styled-content style="font-family:Courier,monospace">SdaiIterator sdaiCreateIterator (SdaiAggr aggregate);
void sdaiDeleteIterator (SdaiIterator iterator);
```

Currently, mnconvert transforms it into:
```asciidoc
[source%unnumbered,code]
--
SdaiIterator sdaiCreateIterator (SdaiAggr aggregate); 
void sdaiDeleteIterator (SdaiIterator iterator); 
--
```
Don't need to encode it as monospace additionally.

**Comment by Intelligent2013** [comment]
Done in `mnconvert-1.27.0`.
