### ISSUE TITLE
XML to ADOC: Paragraph tags are being parsed as subclauses

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mnconvert#292]
In relation to https://github.com/metanorma/iso-10303-detached-docs/issues/118

From ISO 10303 part 24:
```xml
 <p>
      <underline>Original specification in <std std-id="iso:std:iso:10303:-22:en" type="undated">
            <std-ref>ISO 10303-22</std-ref>
         </std>
      </underline>
   </p>
   <p>10.6.5</p>
```

`<p>10.6.5</p>` line is being parsed as a blank clause:

```adoc
===== {blank}
```

I believe that `10.6.5` is in fact a clause acotation from `ISO 10303-22` reference. So maybe this case is an structure error from XML source. But still, parsing issue is evident.

**Comment by Intelligent2013** [comment]
Currently, mnconvert transforms `<p>10.6.5</p>` into
```xml
<sec sec_depth="4">
<label>10.6.5</label>
</sec>
```
in on-fly STS pre-processing XML stage.

This conversion was made specially in https://github.com/metanorma/mnconvert/issues/34 for BSI when title encoded in `p`
```xml
<sec id="sec_intro" sec-type="intro">
<title>Introduction</title>
<p><bold>0.1   General</bold></p>
<p>This document provides guidance that supports the effective
```

Will fix it.

**Comment by Intelligent2013** [comment]
Done in `mnconvert-1.27.0`.
