### ISSUE TITLE
Change folder name from "sources.sts2mn" to "sources.mnconvert"

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#30]
Currently, auto-generated adoc files folder is still named as `sources.sts2mn`.
I suggest to change it to `sources.mnconvert` in order to avoid confusion.

**Comment by ronaldtse** [comment]
@Intelligent2013 I agree, please do so.

**Comment by Intelligent2013** [comment]
Done.

**Comment by manuel489** [comment]
Thanks @Intelligent2013
