### ISSUE TITLE
ISO/IEC Coding Guidelines: reference to the term

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#308]
Source: https://github.com/metanorma/mnconvert/issues/190, https://github.com/metanorma/metanorma-iso/issues/868

Currently, mnconvert creates the element `named-content` for the reference to the term
```
<named-content xlink:href="#term_3.1.1.2" content-type="term">time</named-content>
```
in 'Terms and definitions` section and document's body. This behavior inherited from BSI documents.

From 'IEC/ISO Coding Guidelines':
- '9.3.6 Cross-references between terms in the Terms and definitions clause':
`Cross-references between terminological entries or terms within the Terms and definitions clause can be tagged as <tbx:entailedTerm>. This element should only be used in child elements of <tbx:termEntry>.`

Example:
```xml
<tbx:definition>action to eliminate a detected <tbx:entailedTerm target="term_3.21">nonconformity (3.21)</tbx:entailedTerm></tbx:definition>
```

- '10.1.3 Cross-references to terms':
`Outside the terms and definitions section, references to terms contained within the document should be made using the id in the terminological entry.`
  - ISO:
   ```xml
   <p>This term is defined in <xref ref-type="sec" rid="term_3.3">3.3</xref>.</p>
   ```
  - IEC:
   ```xml
   <p>This term is defined in <xref ref-type="other" rid="con-3.3">3.3</xref>.</p>
   ```

**Comment by ronaldtse** [comment]
@Intelligent2013 could you also help document the STS XML practices of BSI in the same way so that we can keep track of the differences? Thanks!

**Comment by Intelligent2013** [comment]
> @Intelligent2013 could you also help document the STS XML practices of BSI in the same way so that we can keep track of the differences? Thanks!

@ronaldtse I'll do it in https://github.com/metanorma/mnconvert/issues/309.

**Comment by Intelligent2013** [comment]
Done.
