### ISSUE TITLE
Bug: Wrong usage of cross-reference markup

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#31]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

`term:[<anchor>]` approach is being used to cross-reference description list items, like:

````
[[abbrev_1]]CBRMS::
collaborative business relationship management system

[[abbrev_2]]IPR::
intellectual property right

[[abbrev_3]]KPI::
key performance indicator

[[abbrev_4]]MAP::
maturity assessment profile

[[abbrev_5]]OLA::
operating level agreement

[[abbrev_6]]RMP::
relationship management plan

[[abbrev_7]]SER::
senior executive responsible

[[abbrev_8]]SLA::
service level agreement
````

in this way:

````
[[sec_8.2.2.1]]
===== What: summary of the intent

The term:[abbrev_7,SER] appointed by top management (see <<sec_5.3.1>>) is critical
to ensuring the effectiveness of the term:[abbrev_1,CBRMS].
````

This is incorrect as it is referring to a description list element and not a section term per se. Hence, it triggers a compilation error.
The correct markup should be: `<<abbrev_7,SER>>` and `<<abbrev_1,CBRMS>>`

Thanks!

**Comment by Intelligent2013** [comment]
Done. Adoc updated in https://github.com/metanorma/mn-samples-bsi/tree/master/sources.mnconvert.

**Comment by manuel489** [comment]
Thanks @Intelligent2013!
