### ISSUE TITLE
STS -> MN: Incorrect conversion of sub-clauses that pertain to Introduction section

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#34]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

Currently, sub-clauses concerning to the *Introduction* section are typeset as literal bold text.

From BS-ISO-44002:
````
[[introduction]]
== Introduction

*0.1   General*

This document provides guidance that supports the effective implementation of...
````

This is semantically incorrect.
They should be written as actual sub-clauses:
````
[[introduction]]
== Introduction

=== General

This document provides guidance that supports the effective implementation of...
````

Output:
![Capture_1](https://user-images.githubusercontent.com/33627611/126540760-32632f94-0ab4-4a40-95de-629298893c25.PNG)

**Comment by Intelligent2013** [comment]
In the source STS xml it encoded as bold text in paragraph:
```xml
<sec id="sec_intro" sec-type="intro">
<title>Introduction</title>
<p><bold>0.1   General</bold></p>
<p>This document provides guidance that supports the effective
```

Theoretically these issues can be fixed in sts->mn adoc xslt (but not in sts->mn xml xslt). I have to analyze all source xml examples to find conversion rules.

**Comment by Intelligent2013** [comment]
These headers can be catch by regex `^([A-Z]|[0-9]+)(\.[0-9]+(\s.*)?)?$`, where:
- `([A-Z]|[0-9]+)` - matches one upper cased letter or one or more digits
- `\.[0-9]+` - matches `.` and one or more digits
- `(\s.*)` - matched one white-space and any chars
- `(\.[0-9]+(\s.*)?)?` - matches `.1`, `.1 header`, etc.

**Comment by Intelligent2013** [comment]
There are a few cases matches the regex:

1. One `bold` element in `p`, number and text:
```xml
<p><bold>0.1	General</bold></p>
```
2. A few elements `bold` in `p`.
```xml
<p><bold>0.2	Function of the</bold><std><bold><std-ref>ISO 10667 series</std-ref></bold></std></p>
```

3. Not a header (see page 94 for PAS 2030)
```xml
<p><bold>B.1 Measure BFM.1 Cavity wall insulation including that installed in party walls</bold></p>
```

4. One `bold` element in `p`, number only:
```xml
<p><bold>0.5.1</bold></p>
```

As case 3 is not a section header numbers and there is only one such found case, then regex can be simplified:
`^[0-9]+((\.[0-9]+)+(\s.*)?)?$`

**Comment by Intelligent2013** [comment]
Done.

**Comment by manuel489** [comment]
Thanks @Intelligent2013!
Fix confirmed, closing.
