### ISSUE TITLE
BSI amendment table conversion wrong? Table headers must be on same line and strange content

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#350]
This is the Amendments table from BSI STS into Metanorma:

```
[[tab_informal_amd_nat]]
[%unnumbered]
[cols="2400,7600",options="header"]
|===
|Date
|Text affected

|===

```
<img width="300" alt="Screenshot 2023-02-13 at 5 44 19 PM" src="https://user-images.githubusercontent.com/11865/218424221-847b5d66-f742-4e21-a2ca-26fe32646628.png">

I'm not even sure where this content came from?

The table headings are implemented in multiple rows and will fail.

It should be:
```
[[tab_informal_amd_nat]]
[%unnumbered]
[cols="2400,7600",options="header"]
|===
|Date |Text affected

|===

```

**Comment by Intelligent2013** [comment]
> <img width="300" alt="Screenshot 2023-02-13 at 5 44 19 PM" src="https://user-images.githubusercontent.com/11865/218424221-847b5d66-f742-4e21-a2ca-26fe32646628.png">
>
> I'm not even sure where this content came from?

This is a temporarily table from the table auto-layout algorithm in PDF, it occurs when algorithm is fail by some reason. It's a bug in mn2pdf. Will fix.

**Comment by Intelligent2013** [comment]
I can't repeat the 2nd issue.
For:
```
[[tab_informal_amd_nat]]
[%unnumbered]
[cols="2400,7600",options="header"]
|===
|Date
|Text affected

|===
```

and XML looks correct:
```xml
<table id="tab_informal_amd_nat" unnumbered="true">
	<colgroup>
		<col width="24%"/>
		<col width="76%"/>
	</colgroup>
	<thead>
		<tr>
			<th valign="top" align="left">Date</th>
			<th valign="top" align="left">Text affected</th>
		</tr>
	</thead>
</table>
```

But in any case I'll consolidate all header's cell into the one line.

**Comment by Intelligent2013** [comment]
Fixed in mn2pdf (https://github.com/metanorma/mn2pdf/releases/tag/v1.60) and mnconvert (https://github.com/metanorma/mnconvert/releases/tag/v1.41.0)
