### ISSUE TITLE
STS conversion to MN Adoc: Clean up concept mentions encoding in Metanorma AsciiDoc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#359]
## When terms equal

```adoc
door closer ({{door closer,*3.10*,options="noref,noital,linkmention"}}) 
```

With the initial term ("door closer") same as the one in the parentheses, it can be expressed as:

```adoc
{{door closer}}
```

## When terms different

```adoc
{{requirement,requirements}}
```

The first term is the reference term, the latter is the presentation term.

## When term not present

If the term isn't present, then we need to stay with the current implementation:

```adoc
NOTE: For the definition of process, see
{{process,*3.21*,options="noref,noital,linkmention"}}.
```

**Comment by Intelligent2013** [comment]
Regarding 

> ### When terms equal

`door closer` doesn't have any markup in the source NISO STS XML:
```xml
<tbx:definition>device that can be used for holding a door in the open 
position against the action of a door closer (<xref ref-type="sec" rid="sec_3.10">
		<bold>3.10</bold>
	</xref>), and automatically releasing under conditions recommended in this part of <std>
		<std-ref>BS 7273</std-ref>
	</std>
</tbx:definition>
```

I'll try to extract the term from text if following text is `(` + `xref` + `)`.

But there is a problem, when term is different, for instance:
- abbreviation/acronym
```
incorporated in the CIE (<xref ref-type="sec" rid="sec_3.8">
		<bold>3.8</bold>
</xref>)
```
- plural form
```xml
for actuation of automatic release mechanisms (<xref ref-type="sec" rid="sec_3.3">
  <bold>3.3</bold>
</xref>)
```

It's non-trivial task for processing in the XSLT.

**Comment by Intelligent2013** [comment]
mnconvert updated for the case 'When terms equal'.

The terms can't be extracted for the case 'When terms different' because there isn't markup in the source NISO STS XML (see the previous comment).
