### ISSUE TITLE
STS -> MN: numeric bibliographic references not properly converted

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#362]
Document:
* https://github.com/metanorma/mn-samples-bsi/blob/main/reference-docs/bs-codes-of-practice/bs-7273-4-2015-A1-2021/30422111.xml

There is this paragraph that is converted by mnconvert:
```adoc
In England and Wales, adequate means of escape in the event of fire in existing
buildings are required under the Regulatory Reform (Fire Safety) Order 2005
<<ref_34>>. Guidance on this legislation in England and Wales, including the use
of {{release mechanism,release mechanisms}} for doors, is published by the
Department for Communities and Local Government (http://www.gov.uk[www.gov.uk]).
Similar requirements are imposed by equivalent legislation in Scotland
footnote:[The Fire (Scotland) Act 2005 [5] and the Fire Safety (Scotland)
Regulations 2006 [6]. Guidance on the Scottish legislation is published by
Scottish Government (http://www.scotland.gov.uk[www.scotland.gov.uk])**.**] and
Northern Ireland footnote:[The Fire and Rescue Services (Northern Ireland) Order
2006 [7] and Fire Safety Regulations (Northern Ireland) 2010 [8]. Guidance on
the legislation in Northern Ireland is published by Department of Health, Social
Services and Public Safety (http://http://dhsspsni.gov.uk[dhsspsni.gov.uk]).].
In each case, the legislation requires that fire precautions, including
provisions relating to means of escape, be based on a {{fire risk}} assessment.
Throughout Great Britain, the Equality Act 2010 <<ref_39>>, and similar
legislation in Northern Ireland, requires that, in most buildings, reasonable
adjustments to the physical features of premises are carried out to overcome
physical barriers to access. Certain devices actuated by the arrangements
described in this part of <<BS_7273>> are used to overcome such physical
barriers.
```
(reformatted for visibility)

Here, there are a few errors:
* `http://http://dhsspsni.gov.uk[dhsspsni.gov.uk])`
* All the numeric bibliographic tags are not resolved : `[5]`, `[6]`...
* The footnotes are prematurely terminated by the bibliographic tag closing brackets.

The correct output is:
```adoc
In England and Wales, adequate means of escape in the event of fire in existing
buildings are required under the Regulatory Reform (Fire Safety) Order 2005
<<ref_34>>. Guidance on this legislation in England and Wales, including the use
of {{release mechanism,release mechanisms}} for doors, is published by the
Department for Communities and Local Government (http://www.gov.uk[www.gov.uk]).
Similar requirements are imposed by equivalent legislation in Scotland
footnote:[The Fire (Scotland) Act 2005 <<ref_35>> and the Fire Safety (Scotland)
Regulations 2006 <<ref_36>>. Guidance on the Scottish legislation is published by
Scottish Government (http://www.scotland.gov.uk[www.scotland.gov.uk]).] and
Northern Ireland footnote:[The Fire and Rescue Services (Northern Ireland) Order
2006 <<ref_37>> and Fire Safety Regulations (Northern Ireland) 2010 <<ref_38>>. Guidance on
the legislation in Northern Ireland is published by Department of Health, Social
Services and Public Safety (http://dhsspsni.gov.uk[dhsspsni.gov.uk]).].
In each case, the legislation requires that fire precautions, including
provisions relating to means of escape, be based on a {{fire risk}} assessment.
Throughout Great Britain, the Equality Act 2010 <<ref_39>>, and similar
legislation in Northern Ireland, requires that, in most buildings, reasonable
adjustments to the physical features of premises are carried out to overcome
physical barriers to access. Certain devices actuated by the arrangements
described in this part of <<BS_7273>> are used to overcome such physical
barriers.
```

Original:
<img width="582" alt="Screenshot 2023-02-16 at 3 47 06 PM" src="https://user-images.githubusercontent.com/11865/219300655-bb652143-b996-448b-9a19-0b21fb4ecb5b.png">

Generated:
<img width="593" alt="Screenshot 2023-02-16 at 3 47 20 PM" src="https://user-images.githubusercontent.com/11865/219300707-4a8995a5-3442-4343-9066-79cf046cee73.png">

**Comment by ronaldtse** [comment]
Important: a `footnote:[...]` must exist on the same line, otherwise it will be parsed wrongly.

**Comment by ronaldtse** [comment]
Second missing text detected in the same document:
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/11865/219305064-acc46123-27a2-40f9-9683-71e290a87601.png">

**Comment by Intelligent2013** [comment]
> * `http://http://dhsspsni.gov.uk[dhsspsni.gov.uk])`

@ronaldtse the source NISO STS XML issue:
```xml
<ext-link xlink:type="simple" xlink:href="http://http://dhsspsni.gov.uk">dhsspsni.gov.uk</ext-link>
```
Also this error there is in the documents:
- bs-codes-of-practice\bs-7858\
- bs-codes-of-practice\bs-9992\
- standards\bs-202000\

I'll add the fixing this error in the mncovert.

> * All the numeric bibliographic tags are not resolved : `[5]`, `[6]`...

@ronaldtse  `[5]`, `[6]` are hard-coded in the source NISO STS XML:
```xml
<fn id="fn_1">
  <label>1</label>
  <p>The Fire (Scotland) Act 2005 [5] and the Fire Safety (Scotland) Regulations 2006 [6]. Guidance on the Scottish legislation is published by Scottish Government ...
  </p>
</fn>
```
I may try to catch them and resolve via XSLT on-fly in the mnconvert. But I need time to analyze all cases.

> * The footnotes are prematurely terminated by the bibliographic tag closing brackets.

Looks like I have to escape `[` `]` something in footnotes, until I solve the previous issue with resolving `[N]`. Will investigate.


> Second missing text detected in the same document:

I can't repeat this issue:
![image](https://user-images.githubusercontent.com/5559926/219309258-a1bbe95f-7600-4f46-a675-b3e448b7db6f.png)
Please make sure that you use latest mnconvert output. A few days ago the issue with italic markup was fixed, may be the reason in it.

**Comment by ronaldtse** [comment]
Thank you for the investigation. I am using the latest mnconvert from source (the Makefile in mn-samples-bsi).

What a surprise to see so many data source errors... ugh.

Feel free to close this once you're done, since it's a data source error.

**Comment by Intelligent2013** [comment]
> - http://http://dhsspsni.gov.uk[dhsspsni.gov.uk])

Fixed on fly via XSLT in mnconvert.

**Comment by Intelligent2013** [comment]
Another example (adoptions\bs-iso-30042\30338734.xml):
```
... a RelaxNG sample schema is available through the TBX Info website<sup>[15]</sup>
```

```
a RelaxNG sample schema is available through the TBX Info website^[15]^
```

To do: remove superscript for text `[digit(s)]`.

**Comment by Intelligent2013** [comment]
Brackets in `sup` around `xref`:
```xml
<sup>[</sup>
<xref ref-type="bibr" rid="ref_21">
	<sup>15</sup>
</xref>
<sup>]</sup>
```

**Comment by Intelligent2013** [comment]
Done.
