### ISSUE TITLE
STS -> MN: Missing "addendum start" tag when in a clause heading

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#366]
Document XML:
* mn-samples-bsi: https://github.com/metanorma/mn-samples-bsi/blob/main/reference-docs/bs-codes-of-practice/bs-7273-4-2015-A1-2021/30422111.xml

Left generated, right original:
<img width="1576" alt="Screenshot 2023-02-16 at 8 56 23 PM" src="https://user-images.githubusercontent.com/11865/219370827-d4a54fe2-9e75-4d64-a932-7b421fe97e1a.png">

This is in Annex A.

The resulting code is:
```adoc
=== Safety and securityadd:[ace-tag_A1_end]

Where such facilities are provided for accessibility...
```

But should be:
```adoc
=== add:[ace-tag_A1_start]Safety and securityadd:[ace-tag_A1_end]

Where such facilities are provided for accessibility...
```

**Comment by Intelligent2013** [comment]
They put `start` tag at the label:
```
<label>A.3 <named-content content-type="ace-tag" specific-use="A1_start"/>
</label>
<title>Safety and security<named-content content-type="ace-tag" specific-use="A1_end"/>
</title>
```
but I don't process such case.
Will fix.

**Comment by ronaldtse** [comment]
Thanks! Their practices are so strange!!!

**Comment by Intelligent2013** [comment]
Done.
