### ISSUE TITLE
MN -> PDF: Bibliographic cross-references rendering inside square brackets

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#38]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

Bibliographic cross-references are showing up inside square brackets.

From iso-10667-2:
![issue1-3(from iso-10667-2)](https://user-images.githubusercontent.com/33627611/127774609-785e7cda-42aa-4cb4-bf13-32b21dd4f691.PNG)

*original*:
![issue1-3(from iso-10667-2-original)](https://user-images.githubusercontent.com/33627611/127774697-1d8ee182-3bde-4838-b6e2-179353c88c17.PNG)

Another example from bs-7858:
![issue1-4(from bs-7858)](https://user-images.githubusercontent.com/33627611/127774704-14d2f319-a72c-49f3-a193-1abd6e82357e.PNG)

*original*:
![issue1-4(from bs-7858-original)](https://user-images.githubusercontent.com/33627611/127774758-a1492e3c-598b-46cb-8ea8-e337a58a36fe.PNG)

**Comment by Intelligent2013** [comment]
Source STS XML:
```xml
<std><std-ref>ISO 10667‑1<?doi https://doi.org/10.3403/BSISO10667?></std-ref></std> provides requirements and guidance for the client.
...
<ref-list content-type="bibl" id="sec_bibl"><title>Bibliography</title>
...
   <ref content-type="standard" id="ref_3"><label>[2]</label><std><std-ref>ISO 10667‑1<?doi https://doi.org/10.3403/BSISO10667?></std-ref>, <title>Assessment service delivery — Procedures and methods to assess people in work and organizational settings — Part 1: Requirements for the client</title></std></ref>
...
```

Adoc (generated by adoc):
```adoc
<<ref_3>> provides requirements and guidance for the client.
...
[bibliography]
== Bibliography
...
* [[[ref_3,(ISO 10667-1)2]]], _Assessment service delivery — Procedures and methods to assess people in work and organizational settings — Part 1: Requirements for the client_
```
xml (generated by metanorma gem):
```xml
<eref type="inline" bibitemid="ref_3" citeas="[ISO 10667-1]">[ISO 10667-1]</eref> provides requirements and guidance for the client.
...
<bibitem id="ref_3">
<formattedref format="application/x-isodoc+xml">
<em>Assessment service delivery &#8212; Procedures and methods to assess people in work and organizational settings &#8212; Part 1: Requirements for the client</em>
</formattedref>
<docidentifier type="metanorma">[ISO 10667-1]</docidentifier>
<docidentifier type="metanorma">[2]</docidentifier>
</bibitem>
```

**Comment by Intelligent2013** [comment]
The format
```adoc
* [[[ref_3,(ISO 10667-1)2]]]
```
made in https://github.com/metanorma/sts2mn/issues/64

**Comment by Intelligent2013** [comment]
Regarding https://www.metanorma.org/author/topics/document-format/bibliography/#named-reference-tag-with-automatic-reference-fetching 
```adoc
* [[[{anchor},({reference tag}){reference identification code}]]], _{reference list text}_
```
we need to change the format to:
```adoc
* [[[ref_3,(2)ISO 10667-1]]]
```
But in this case resulted xml:
```xml
<eref type="inline" bibitemid="ref_3" citeas="[18]">[18]</eref> provides requirements and guidance for the client. This document provides requirements and guidance for the service provider.
```


@manuel489 I don't have much experience in metanorma asciidoc markup as you. Could you clarify, how should we markup this, if we need to show `ISO 10667-1` in the text, and show `[2]` in the Bibliography section?
![image](https://user-images.githubusercontent.com/5559926/127842543-fb9a4243-e200-422a-b224-f28e82481ce8.png)

**Comment by Intelligent2013** [comment]
Regarding bs-7858,
source STS XML has square brackets in the text around reference:
```xml
<non-normative-note>
	<label>NOTE 5</label>
	<p>Attention is drawn to the Rehabilitation of Offenders Act 1974 [<xref ref-type="bibr" rid="ref_5">2</xref>], the ...
</non-normative-note>
```
adoc (mnconvert):
```adoc
NOTE: Attention is drawn to the Rehabilitation of Offenders Act 1974 [<<ref_5>>], the 
```
I have to cut it in sts->mn conversion.

**Comment by manuel489** [comment]
> @manuel489 I don't have much experience in metanorma asciidoc markup as you. Could you clarify, how should we markup this, if we need to show ISO 10667-1 in the text, and show [2] in the Bibliography section?

Hey @Intelligent2013, yes we need to show the reference as it's shown in original source.
And, as you indicated above, the correct markup for the reference is:
````
* [[[ref_3,(2)ISO 10667-1]]], _Assessment service delivery — Procedures and methods to assess people in work and organizational settings — Part 1: Requirements for the client_
````

This should give an output in PDF just as it's given in HTML output:
![Capture1](https://user-images.githubusercontent.com/33627611/127893764-4950ea58-38ef-4ffc-beeb-d1d2b5d49dc7.PNG)


From part of the XML:
```xml
...
<docidentifier type="ISO">ISO 10667-1</docidentifier><docidentifier type="metanorma">[23]</docidentifier>
...
```

We need to place first the `docidentifier type="metanorma"`, second the `docidentifier type="ISO"`, and then the rest.

**Comment by Intelligent2013** [comment]
Double brackets issue for bs-7858 fixed:

![image](https://user-images.githubusercontent.com/5559926/128224034-8e4018c4-1fee-4377-bec3-ff6bdad4e3de.png)

**Comment by manuel489** [comment]
@Intelligent2013, now the references are showing duplicated:

*from bs-en-iso-56003*:
![capture1](https://user-images.githubusercontent.com/33627611/135554260-42846a0d-e8d8-419d-9fe4-278026f33fa5.PNG)

Original:
![capture1_original](https://user-images.githubusercontent.com/33627611/135554388-a9386029-b345-4f53-bb33-a68034b5078b.PNG)

Must be a collateral fault.

**Comment by Intelligent2013** [comment]
> now the references are showing duplicated

issue fixed (there was side effect of fixing https://github.com/metanorma/bs-202000/issues/3#issuecomment-923222075)
![image](https://user-images.githubusercontent.com/5559926/135731168-a3235acb-37e3-416c-9239-4b752daeef98.png)

**Comment by manuel489** [comment]
Confirmed fixed. Closing.
