### ISSUE TITLE
STS -> MN: Remove additional white space in bibliography markup

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#39]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

In bibliography markup, there should not be white space between closing square brackets and comma.

*From bs-iso-44003*:
````
[bibliography]
== Bibliography

* [[[ref_2,(ISO/TR 44000)1]]]  , _Principles for successful collaborative business relationship management_ 

* [[[ref_3,(ISO 44002)2]]]  , _Collaborative business relationship management systems — Guidelines on the implementation of ISO 44001_ 
````

This generates two commas in a row in output:
![issue2-1](https://user-images.githubusercontent.com/33627611/127775030-dd8a94b6-841f-46f3-a8c8-f55402988315.PNG)

Correct markup should be without white space:

````
* [[[ref_2,(ISO/TR 44000)1]]], _Principles for successful collaborative business relationship management_ 

* [[[ref_3,(ISO 44002)2]]], _Collaborative business relationship management systems — Guidelines on the implementation of ISO 44001_ 
````

**Comment by Intelligent2013** [comment]
The reason - spaces in source STS xml between `ref` and `label` and between `label` and `std`.
```xml
<ref content-type="standard" id="ref_3"> <label>[2]</label> <std std-id
```
To do: remove spaces on the 'normalization xml' stage.

**Comment by Intelligent2013** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/5559926/127856278-b1c69945-c4be-4545-84d9-3606ed624218.png)

**Comment by manuel489** [comment]
Fix confirmed, closing.
