### ISSUE TITLE
STS -> MN: Adjust markup to enable auto-fetch in BSI references.

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#40]
*In relation with https://github.com/metanorma/metanorma-bsi/issues/30*

When it comes to BSI references, we need to make a little adjustment in the document identifier.

From *bs-en-12973*:
````
* [[[EN_1325,EN 1325]]], _Value Management - Vocabulary - Terms and definitions_

* [[[EN_16271,EN 16271]]], _Value management - Functional expression of the need and functional performance specification - Requirements for expressing and validating the need to be satisfied within the process of purchasing or obtaining a product_
````

In order to enable auto-fetch, we need to place a `BS`   at the beginning of the document identifier.
Like this:
````
* [[[EN_1325,BS EN 1325]]], ...

* [[[EN_16271,BS EN 16271]]], ...
````

**Comment by Intelligent2013** [comment]
BS prefix added for references that start with 'EN '.

**Comment by ronaldtse** [comment]
This is a larger problem about adopted documents and their references. We will need to discuss with @opoudjis on what the correct treatment is.

**Comment by manuel489** [comment]
@ronaldtse, I've confirmed that this is fixed. At least the part described above.
Should we close the ticket or should we wait for further instructions?

**Comment by ronaldtse** [comment]
"BS EN" means it's an adopted document. In an adopted document, by default, the references should be kept identical to the original document. This means that it's "EN" references are exactly that -- "EN" not "BS EN". 

Sometimes, the adoption of the adopted document may include changes, such as changing of references from "EN" to "BS EN" or "BS". 

Currently Metanorma does not officially (yet) implement the concept of "adoption". This means that there is no correct practice on how to tweak content in adopted documents. 

Let's call this a day right now and revisit once Metanorma supports adoption.
