### ISSUE TITLE
STS -> MN: Escape "(c)" text to avoid render copyright symbol

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#41]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

Whenever there is a `(c)` or `(C)`, we need to escape it with a *Zero Width Non Joiner* character in order to avoid copyright symbol.
By doing: `(&#x200c;c)`.

For example, to avoid this situation from *bs-en-12973*:
````
**(b) Function analysis**

See <<sec_A.1.3>>.

**(c) Study of solution**

Study of solutions based on a cost-performance optimization, the constraints of the program being taken into account (use of term:[value,Value] Analysis/term:[value,Value] Engineering).

**(d) Monitoring objective costs**

Continuously monitored objective costs, to be expressed in inflation-adjusted currency units.
````

Output:
![issue5-generated](https://user-images.githubusercontent.com/33627611/127951204-b93ddce7-25a6-471a-b4c3-60382b91c55c.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/128166929-723136ef-e560-472b-a241-7832145b907c.png)

**Comment by manuel489** [comment]
Fix confirmed, closing.
