### ISSUE TITLE
STS -> MN: Incorrect markup of Introduction section

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#42]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

From *bs-en-iso-56002*:
````
[[introduction]]
== 0   Introduction

=== General

An organization’s ability to innovate is recognized as a key factor for sustained growth, economic viability, increased well-being, and the development of society.
...
````

Output:
![issue3-generated](https://user-images.githubusercontent.com/33627611/128615536-1d3859ff-b7f5-4025-aa8a-673a2af9b8d0.PNG)

Correct markup should be:
````
[[introduction]]
== Introduction
...
````

**Comment by Intelligent2013** [comment]
Source STS XML issue - title starts with digit:
```xml
<sec id="sec_intro" sec-type="intro">
	<title>0   Introduction</title>
	<p>
		<bold>0.1   General</bold>
	</p>
```

To do fix in the linearization stage: in the element `sec` doesn't contain the element `label`, then initial digits from the element `title` should be removed.

**Comment by Intelligent2013** [comment]
Fixed:
```adoc
[[introduction]]
== Introduction
```

**Comment by manuel489** [comment]
Fix confirmed, closing.
