### ISSUE TITLE
STS -> MN: Remove prepended white space in bold paragraphs

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#43]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

There are some bold paragraphs that include white space at the beginning.
This generates a rendering error in output. It shows them as if they were figure blocks.

From *bs-en-iso-56003*:
````
[[sec_E.1]]
=== Monitoring, measurement, analysis, and evaluation

 **The organization should determine:** 

. what needs to be monitored and measured, including which innovation performance indicators are to be used,
. the tools and methods for monitoring, measurement, analysis and evaluation, as applicable to ensure valid results,
. when and how the monitoring and measuring should be performed,
. when the results from monitoring and measurement should be analyzed and evaluated, and
. who will be responsible.

 **The set of innovation performance indicators, quantitative or qualitative, can include a balance of:** 

. input-related indicators, e.g. number of ideas, number of innovation initiatives value-creation potential of ideas, new sources of knowledge, new insights, resources, and competence, leading indicators.
````

Output:
![issue4-generated](https://user-images.githubusercontent.com/33627611/128615699-7953979d-7d09-4365-a13c-145d9ecbccdc.PNG)

**Comment by Intelligent2013** [comment]
Source STS XML has a space between `p` and `bold`:
```xml
<p> <bold>The organization should determine:</bold> </p>
```

Todo: remove leading spaces in the xslt on-fly.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/128713686-1851d843-aa3d-46a2-9437-e3ee9e4e60a6.png)

**Comment by manuel489** [comment]
Fix confirmed, closing.
