### ISSUE TITLE
STS -> MN: Image are missing in BS ISO 30042

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#46]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

Image files are missing in [BS ISO 30042](https://github.com/metanorma/mn-samples-bsi/tree/master/sources.mnconvert/adoptions/bs-iso-30042).
I can extract them if required. (Thought I had done it already.)

**Comment by Intelligent2013** [comment]
@manuel489 you can find the message about missing images here:
https://github.com/metanorma/mn-samples-bsi/runs/3270153970?check_suite_focus=true#step:3:6688
```
Can't copy file: java.nio.file.NoSuchFileException: /home/runner/work/mn-samples-bsi/mn-samples-bsi/reference-docs/adoptions/bs-iso-30042/images/30042_ed2fig1.png
Can't copy file: java.nio.file.NoSuchFileException: /home/runner/work/mn-samples-bsi/mn-samples-bsi/reference-docs/adoptions/bs-iso-30042/images/30042_ed2fig2.png
Can't copy file: java.nio.file.NoSuchFileException: /home/runner/work/mn-samples-bsi/mn-samples-bsi/reference-docs/adoptions/bs-iso-30042/images/30042_ed2fig3.png
Can't copy file: java.nio.file.NoSuchFileException: /home/runner/work/mn-samples-bsi/mn-samples-bsi/reference-docs/adoptions/bs-iso-30042/images/30042_ed2fig4.png
```

In the source XML STS there are xml processing instructions `<?isoimg-id...` like this:
```xml
<graphic xlink:href="fig_1"><?isoimg-id 30042_ed2fig1.EPS?></graphic>
```

It means that image should has name `30042_ed2fig1.png`, not `fig_1.png`

**Comment by manuel489** [comment]
@Intelligent2013
In *bs-7000-4*, Figure 1 is missing in *sources.mnconvert* folder
and it is present in *reference-docs/bs-guides/bs-7000-4/images/* folder.

**Comment by Intelligent2013** [comment]
> In bs-7000-4, Figure 1 is missing in sources.mnconvert folder
> and it is present in reference-docs/bs-guides/bs-7000-4/images/ folder.

@manuel489 issue fixed, now image there.

**Comment by manuel489** [comment]
Thank you @Intelligent2013!
Closing
