### ISSUE TITLE
STS -> MN: Incorrect assignation of section numbers in Terms and Definitions

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#50]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

From *bs-en-iso-56000*:
![issue2-generated](https://user-images.githubusercontent.com/33627611/128615209-3e6080bf-41d9-41c2-be2b-4f9dcd54e290.PNG)

Original:
![issue2-original](https://user-images.githubusercontent.com/33627611/128615213-a5bcc3b5-2324-49ea-99bd-fb8d0ab7cb10.PNG)

XML source seems to indicate the correct section numbers.

**Comment by ronaldtse** [comment]
@manuel489 does the "original" assign clause "3.1.1" to the term "innovation"? That's very strange.

<img width="280" alt="Screenshot 2021-08-09 at 9 36 59 AM" src="https://user-images.githubusercontent.com/11865/128652647-9e272d88-a7a8-409c-872b-2887278e3031.png">

**Comment by manuel489** [comment]
@ronaldtse yes,
![issue1-original](https://user-images.githubusercontent.com/33627611/128655452-deeb4b1d-9aad-4e78-9139-eac77954895d.PNG)

Why it's strange?

**Comment by ronaldtse** [comment]
Because 3.1.1 as a term should not have a sub clause of 3.1.1.1. Only if 3.1.1 is a term collection should it contain 3.1.1.1. This is because if I quote 3.1.1, the reader does not know if I also mean 3.1.1.1 and 3.1.1.2.

**Comment by manuel489** [comment]
Well, from my point of view, if I quote 3.1.1, I would be referring to the definition of "innovation" without including its sub-clauses. I mean the text: *"new or changed entity (3.2.5), realizing or redistributing value (3.7.6)"* and the subsequent notes.
And, if I'd want to refer to the sub-clauses, I would do: *radical innovation (3.1.1.1)* or *disruptive innovation (3.1.1.2)*, right?

Probably the approach is conceptually wrong (I don't know). But I don't find it confusing to the reader.

**Comment by ronaldtse** [comment]
In ISO speak this is called a "hanging paragraph". An ISO document is in a tree structure. Logically what belongs to 3.1.1 is everything under the clause labeled 3.1.1 -- without resorting to mental gymnastics. This is in violation of the ISO/IEC Directives and should never have been approved like this.

**Comment by manuel489** [comment]
Ok, so should we leave it as it is then?

**Comment by Intelligent2013** [comment]
Regarding source STS XML, `term-sec id="sec_3.1.1.1">`  arranges below `<sec id="sec_3.1">`, is not nested: 
```xml
<sec id="sec_3" sec-type="terms">
	<label>3</label>
	<title>Terms and definitions</title>
	<sec id="sec_3.1">
		<label>3.1</label>
		<title>General terms related to innovation</title>
		<term-sec id="sec_3.1.1">
			<label>3.1.1</label>
			<tbx:termEntry id="term_3.1.1">
				<tbx:langSet xml:lang="en">...
					<tbx:tig id="term_3.1.1-1">
						<tbx:term>innovation</tbx:term>...
					</tbx:tig>
				</tbx:langSet>
			</tbx:termEntry>
		</term-sec>
		<term-sec id="sec_3.1.1.1">
			<label>3.1.1.1</label>
			<tbx:termEntry id="term_3.1.1.1">
				<tbx:langSet xml:lang="en">...
					<tbx:tig id="term_3.1.1.1-1">
						<tbx:term>radical innovation</tbx:term>...
					</tbx:tig>
					<tbx:tig id="term_3.1.1.1-2">
						<tbx:term>breakthrough innovation</tbx:term>...
					</tbx:tig>
				</tbx:langSet>
			</tbx:termEntry>
		</term-sec>
		<term-sec id="sec_3.1.1.2">
			<label>3.1.1.2</label>
			<tbx:termEntry id="term_3.1.1.2">
				<tbx:langSet xml:lang="en">...
					<tbx:tig id="term_3.1.1.2-1">
						<tbx:term>disruptive innovation</tbx:term>...
					</tbx:tig>
				</tbx:langSet>
			</tbx:termEntry>
		</term-sec>
		<term-sec id="sec_3.1.2">
			<label>3.1.2</label>
			<tbx:termEntry id="term_3.1.2">
				<tbx:langSet xml:lang="en">...
					<tbx:tig id="term_3.1.2-1">
						<tbx:term>management</tbx:term>...
					</tbx:tig>
				</tbx:langSet>
			</tbx:termEntry>
		</term-sec>
```

mnconvert calculates depth of title (count of `=` before title in adoc markup) based on nesting level of elements, but not level in the element `label`. But may be need to do:
- additionally calculated the depth based on text in the element `label` (count of `.` + 1)
- if label`s depth isn't equal to nesting level, then use label`s depth and print warning about this case?

**Comment by ronaldtse** [comment]
> This is in violation of the ISO/IEC Directives and should never have been approved like this.

@manuel489 sorry I was wrong. @opoudjis and I talked about this issue and delve into references, and apparently this is a supported form of numbering in ISO 10241-1.

Here's the relevant section from ISO 10241-1:

<img width="798" alt="Screenshot 2021-08-09 at 9 41 17 PM" src="https://user-images.githubusercontent.com/11865/128715755-31cbbd8f-bc05-467e-9a23-8e2231a04561.png">

So this is something we have to support. Will ticket.

**Comment by opoudjis** [comment]
Addressed:

If you want a term to contain another term (and yes, I know that's not what ISO thinks is going on here), the outer term needs to be marked up with `[.term]`:

````
[.term]
=== Terminological entry at first level of concept system

==== Terminological entry at second level of concept system
````

**Comment by ronaldtse** [comment]
@opoudjis clarification on https://github.com/metanorma/mnconvert/issues/50#issuecomment-905727997 needed, thanks.

**Comment by opoudjis** [comment]
````
====== Terminological entry at fourth level of concept system

Definition 4.
````

will not be recognised by Asciidoctor. Per https://www.metanorma.org/author/topics/document-format/sections/#sections-deeper-than-5-levels , you will need to change it to:

````
[level=6]
===== Terminological entry at fourth level of concept system

Definition 4.
````

I've just run this through metanorma-iso, and it is generating:

````
<term id="term-terminological-entry-at-first-level-of-concept-system"><preferred>Terminological entry at first level of concept system</preferred><definition><p id="_ee0a97f4-0ca7-4ce9-91b7-9bd48c9d23f0">Definition 1.</p></definition>
<term id="term-terminological-entry-at-second-level-of-concept-system"><preferred>Terminological entry at second level of concept system</preferred><definition><p id="_a3c3fee7-df6e-4b8a-a7f2-e979e78bdf75">Definition 2.</p></definition>
<term id="term-terminological-entry-at-third-level-of-concept-system">
<preferred>Terminological entry at third level of concept system</preferred>
<definition><p id="_70892424-3449-48e3-bd70-b9cd60e3d2c6">Definition 3.</p></definition>
</term>
<term id="term-terminological-entry-at-fourth-level-of-concept-system">
<preferred>Terminological entry at fourth level of concept system</preferred>
<definition><p id="_361200c2-6f7d-45cc-b3e7-b2516643391c">Definition 4.</p></definition>
</term></term></term>
````

Since each clause is being treated as a `term`, they will be referenced and numbered correctly. Does this address your concern, @ronaldtse ?

**Comment by ronaldtse** [comment]
```xml
<term id="term-terminological-entry-at-first-level-of-concept-system"><preferred>Terminological entry at first level of concept system</preferred><definition><p id="_ee0a97f4-0ca7-4ce9-91b7-9bd48c9d23f0">Definition 1.</p></definition>
<term id="term-terminological-entry-at-second-level-of-concept-system"><preferred>Terminological entry at second level of concept system</preferred><definition><p id="_a3c3fee7-df6e-4b8a-a7f2-e979e78bdf75">Definition 2.</p></definition>
<term id="term-terminological-entry-at-third-level-of-concept-system">
<preferred>Terminological entry at third level of concept system</preferred>
</term>
</term>
</term>
```
@opoudjis I feel that using `<term>` as a hierarchical construct in the XML is not ideal. We should probably encode the concept hierarchy separately from the collection of terms in the semantic XML?

**Comment by Intelligent2013** [comment]
@manuel489 initial issue fixed and now the terms rendered so:
![image](https://user-images.githubusercontent.com/5559926/139886052-f98891b5-5690-46d4-a95f-8f21cb908a29.png)

note: the messages `term ... not resolved via ID` relate to https://github.com/metanorma/metanorma-standoc/issues/550

**Comment by manuel489** [comment]
Confirmed fixed. Closing.
