### ISSUE TITLE
STS -> MN: Parse MathML code into AsciiMath in BSI PDF layout

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#54]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

From *bs-8887-1-2006*:
![issue1-generated](https://user-images.githubusercontent.com/33627611/129062172-b5c5a4c3-3540-4c80-94bc-a680d6db97ec.PNG)

Markup seems to be incorrect since MathML code is not being parsed:
````
stem:[<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1">
<mrow>
<msub>
<mi>P</mi>
<mtext>t</mtext>
</msub>
<mo>+</mo>
<msub>
<mi>P</mi>
<mtext>c</mtext>
</msub>
<mo>=</mo>
<mrow>
...
````

Original:
![issue1-original](https://user-images.githubusercontent.com/33627611/129062196-ad35cd47-2c4b-4bd2-bb83-8c6ec6e4232c.PNG)

Correct markup would look like:
````
[stem]
++++
P_t + P_c = [(C_{"dev"} + C_{"mkt"})//Q_{"at"}] + C_{"mat"} + C_{"ma"} + C_{"de"}
++++
````

Unless there is a way to directly render MathML code?

In addition, the description of math symbols should be marked up as description lists
instead of table, namely:
````
stem:[P_o]:: is that portion of the selling price contributing
to the manufacturer’s overhead cost and the required profit;
stem:[C_{"dev"}]:: is the cost of developing the product
(for total anticipated quantity);
...
````

**Comment by manuel489** [comment]
Maybe the parsing is not necessary.
Let's put this ticket on hold until I find a solid answer.

**Comment by ronaldtse** [comment]
Let's ask @opoudjis on this. There should be a way to support inline MathML.

**Comment by manuel489** [comment]
And yes! We do support native MathML code in Asciidoc markup. I have confirmed it.
So @Intelligent2013, the proper markup (without parsing anything) would be:
````
[stem]
++++
<MathML code>
++++
````

Maybe the error above was caused for the use of an inline stem macro instead of stem block.

**Comment by ronaldtse** [comment]
@manuel489 but what about "inline" math? i.e. not a separate block. I suspect we'd be better served by a new command `mathml:[]...` and

```
[mathml]
++++
<MathML code>
++++
```

**Comment by manuel489** [comment]
> @manuel489 but what about "inline" math? i.e. not a separate block.

@ronaldtse, it does work for simple equations. But not for the above equation.

![issue1-generated](https://user-images.githubusercontent.com/33627611/129198501-3cc791df-6254-4b2b-9839-abe62e8215bc.PNG)

Original equation:
![issue2-original](https://user-images.githubusercontent.com/33627611/129198597-a5f979fc-b91b-47f0-b0b3-c9e4a5089068.PNG)

At first, I thought it was because the square brackets contained in the equation.
But even if I remove them, the equation renders badly.

> I suspect we'd be better served by a new command mathml:[]...

This does work as well. But the equation numbering is removed
and it seems to work only for separate blocks (not inline):
````
Inline math 1: stem:[<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1">
<mrow>
<msub>
<mi>P</mi>
<mtext>t</mtext>
</msub>
</math>]

Inline math 2: mathml:[<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1">
<mrow>
<msub>
<mi>P</mi>
<mtext>t</mtext>
</msub>
</math>]
````

renders:
![issue1_3-generated](https://user-images.githubusercontent.com/33627611/129199752-bac4949c-c66e-44bb-b14c-53db69bf9f86.PNG)

**Comment by manuel489** [comment]
@opoudjis I did escape `]` with `\]`:
````
stem:[<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1">
<mrow>
<msub>
<mi>P</mi>
<mtext>t</mtext>
</msub>
<mo>+</mo>
<msub>
<mi>P</mi>
<mtext>c</mtext>
</msub>
<mo>=</mo>
<mrow>
<mo>[</mo>
<mrow>
<mrow>
<mo>(</mo>
<mrow>
<msub>
<mi>C</mi>
<mrow>
<mtext>dev</mtext>
</mrow>
</msub>
<mo>+</mo>
<msub>
<mi>C</mi>
<mrow>
<mtext>mkt</mtext>
</mrow>
</msub>
</mrow>
<mo>)</mo>
</mrow>
<mo>/</mo>
<msub>
<mi>Q</mi>
<mrow>
<mtext>at</mtext>
</mrow>
</msub>
</mrow>
<mo>\]</mo>
</mrow>
<mo>+</mo>
<msub>
<mi>C</mi>
<mrow>
<mtext>mat</mtext>
</mrow>
</msub>
<mo>+</mo>
<msub>
<mi>C</mi>
<mrow>
<mtext>ma</mtext>
</mrow>
</msub>
<mo>+</mo>
<msub>
<mi>C</mi>
<mrow>
<mtext>de</mtext>
</mrow>
</msub>
</mrow>
</math>]
````

and what I get is a malformed equation:
![cap2](https://user-images.githubusercontent.com/33627611/129720655-a340e51a-df3f-4214-ba53-235c3a278e2c.png)

**Comment by ronaldtse** [comment]
Re: `stem:[ ]`. We looking for something to enter MathML. We have `latexmath:[]`, `asciimath:[]`. `stem:[]` is just a shorthand right now.

**Comment by Intelligent2013** [comment]
I've tried to escape `]` inside `stem`:
```adoc
stem:[<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1">
<mrow>
<msub>
<mi>P</mi>
<mtext>t</mtext>
</msub>
<mo>+</mo>
<msub>
<mi>P</mi>
<mtext>c</mtext>
</msub>
<mo>=</mo>
<mrow>
<mo>[</mo>
<mrow>
<mrow>
<mo>(</mo>
<mrow>
<msub>
<mi>C</mi>
<mrow>
<mtext>dev</mtext>
</mrow>
</msub>
<mo>+</mo>
<msub>
<mi>C</mi>
<mrow>
<mtext>mkt</mtext>
</mrow>
</msub>
</mrow>
<mo>)</mo>
</mrow>
<mo>/</mo>
<msub>
<mi>Q</mi>
<mrow>
<mtext>at</mtext>
</mrow>
</msub>
</mrow>
<mo>\]</mo>
</mrow>
<mo>+</mo>
<msub>
<mi>C</mi>
<mrow>
<mtext>mat</mtext>
</mrow>
</msub>
<mo>+</mo>
<msub>
<mi>C</mi>
<mrow>
<mtext>ma</mtext>
</mrow>
</msub>
<mo>+</mo>
<msub>
<mi>C</mi>
<mrow>
<mtext>de</mtext>
</mrow>
</msub>
</mrow>
</math>]
```
but resulted metanorma xml looks differently (strange sequence `<mo>&#150;0&#151;</mo>`):
```xml
<stem type="MathML">
	<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1">
		<mrow>
			<msub>
				<mi>P</mi>
				<mtext>t</mtext>
			</msub>
			<mo>&#150;0&#151;</mo>
			<msub>
				<mi>C</mi>
				<mrow>
					<mtext>mkt</mtext>
				</mrow>
			</msub>
		</mrow>
		<mo>)</mo>
		<mo>/</mo>
		<msub>
			<mi>Q</mi>
			<mrow>
				<mtext>at</mtext>
			</mrow>
		</msub>
		<mo>]</mo>
		<mo>&#150;1&#151;</mo>
		<msub>
			<mi>C</mi>
			<mrow>
				<mtext>ma</mtext>
			</mrow>
		</msub>
		<mo>+</mo>
		<msub>
			<mi>C</mi>
			<mrow>
				<mtext>de</mtext>
			</mrow>
		</msub>
	</math>
	<!-- P_t &#150;0&#151; C_((mkt)) ) // Q_((at)) ] &#150;1&#151; C_((ma)) + C_((de)) -->
</stem>
```

Source mathml rendering:
![image](https://user-images.githubusercontent.com/5559926/132688311-88f829e6-c99c-41d3-a157-53aac371ae66.png)

Metanorma mathml rendering:
![image](https://user-images.githubusercontent.com/5559926/132688410-a8c8da11-f683-4fb8-a422-aa3921525350.png)

Should I escape something else?

**Comment by ronaldtse** [comment]
For a long formula like this we should probably use block syntax?

**Comment by Intelligent2013** [comment]
> For a long formula like this we should probably use block syntax?

@ronaldtse yes, it's working. And no need to escace anything:

```adoc
[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1">
...
+++
```
![image](https://user-images.githubusercontent.com/5559926/132690662-866fed4c-7e6a-4368-8554-59e8b1b2a0c1.png)

but what if such expression should be inlined in the text?

**Comment by ronaldtse** [comment]
@Intelligent2013 yes you're right. The problem is with the AsciiDoc parser in general that cannot properly escape, the `]` character when inline.

There is no good, deterministic solution for inline escaping of `]`, e.g. if a math formula contains two `]`.

**Comment by Intelligent2013** [comment]
mnconvert updated:
- source STS xml element `disp-formula` encoded as block `[stem]`
- description of math symbols marked up as description lists instead of table
Resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/132717174-d9d086fa-7168-40a6-bd49-63a83a3839ce.png)

**Comment by manuel489** [comment]
Confirmed fixed. Closing.
