### ISSUE TITLE
STS -> MN: Escape trademark symbol (R)

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#57]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

Replace `(R)` for `(&#x200c;R)` to avoid rendering trademark symbol.

From *bs-7000-4*:
````
[[tab_2]]
.Checklist for management responsibilities
[cols="5000,1500,1500,2000",options="header,footer",headerrows=2]
|===
.2+|Responsibility
|Primary responsibility (singular)
|Subsidiary responsibilities (could be multiple)
.2+|Notes
|(R) footnote:[R = Responsible, A = Authorise, C = Contribute, 1 = Inform (keep informed).]
|(R A C l) footnote:[R = Responsible, A = Authorise, C = Contribute, 1 = Inform (keep informed).]
...
````

renders:
![issue1-generated](https://user-images.githubusercontent.com/33627611/129287862-20870937-f68c-4e80-9fc2-aaed3265c638.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/129456280-79392341-e53a-4073-aa58-6c6bbe923212.png)

**Comment by manuel489** [comment]
Fix confirmed, closing.
