### ISSUE TITLE
STS -> MN: Remove boilerplate text from bibliography section

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#58]
*In relation https://github.com/metanorma/metanorma-bsi/issues/30*

In *bs-11000-2*, the boilerplate text is marked up as sub-clause.

From *bs-11000-2*:
````
[bibliography]
== Bibliography


[bibliography]
=== Standards publications


[bibliography]
=== For dated references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

* [[[ref_1,BS 11000-1]]], _Collaborative business relationships — Part 1: A framework specification_

* [[[ref_2,BS ISO 10667-1]]], _Assessment service delivery — Procedures and methods
* to assess people in work and organizational settings — Part 1: Requirements for the client_

* [[[ref_3,BS ISO 10667-2]]], _Assessment service delivery — Procedures and methods
* to assess people in work and organizational settings — Part 2: Requirements for service providers_
````

renders:
![issue3-generated](https://user-images.githubusercontent.com/33627611/129291107-cead67e2-9bfb-44ae-a67b-1be2bb3cc70f.PNG)

**Comment by Intelligent2013** [comment]
Source STS xml issue, the sentence `For dated references,` encoded in the element `title`, instead of `p`:
```
<ref-list>
   <title>For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.</title>
```

To do: update xslt to remove ref-list/title starts-with `For dated references` (similar to `p`, see https://github.com/metanorma/mnconvert/issues/52).

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/129485254-3e89498a-c5e8-4102-8f14-86a1354ba2e2.png)

**Comment by manuel489** [comment]
Fix confirmed, closing.
