### ISSUE TITLE
Generate term references

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#64]
Previous tickets: https://github.com/metanorma/sts2mn/issues/26
https://github.com/metanorma/bs-202000/pull/8

Initially, term reference was represented as:
`<<term-organization,organization>>`
Then, changed to `term:[xxx]` (or `term:[rendered,original]`).
And, finally, changed to to `{{original,rendered}}`.

Regarding https://github.com/metanorma/metanorma-bsi/issues/70#issuecomment-896085131:
> References to terms are only displayed as hyperlinks with a clause number for parentheses in the first instance they are mentioned in a terms section. Subsequent mentions in the terms section, and mentions elsewhere in the document, are neither hyperlinked nor followed by a clause number. The markup of the reference in that case is only done by us for semantic reasons.

metanorma xml doesn't contain all term references as in the source STS xml.

For example, BS 202000, there are the elements `named-content`:
```xml
<sec id="sec_1" sec-type="scope">
	<label>1</label>
	<title>Scope</title>
	<p>This British <named-content content-type="term" xlink:href="#term_3.26">Standard</named-content> specifies <named-content content-type="term" xlink:href="#term_3.24">requirements</named-content> for an SMS in order to identify measurable criteria for effective SM and instil organizational cultures and behaviours to deliver vendor and supplier confidence with regards to standardization.</p>
</sec>
```
adoc (mnconvert):
```adoc
== Scope

This British {{standard,Standard}} specifies {{requirement,requirements}} for an SMS in order to identify measurable criteria for effective SM and instil organizational cultures and behaviours to deliver vendor and supplier confidence with regards to standardization.
```

Metanorma xml (there aren't term's references):
```xml
<clause id="_scope" type="scope" inline-header="false" obligation="normative" displayorder="5">
	<title depth="1">1<tab/>Scope</title>
	<p id="_">This British Standard specifies requirements for an SMS in order to identify measurable criteria for effective SM and instil organizational cultures and behaviours to deliver vendor and supplier confidence with regards to standardization.</p>
</clause>
```

If  we'll revert back the markup to `<<standard,Standard>>` for terms in the non-terms sections, and for non-first instance mentioned in a terms section, then this will allow us not to lose the original term's references, and resulted metanorma xml will contain term's reference in the element `xref`:
```xml
This British <xref target="standard">Standard</xref> ...
```

@ronaldtse should I do it?

**Comment by ronaldtse** [comment]
The only correct way to refer to a term is the '{{}}' syntax. There are only two possibilities here:
1. The term referenced is not present in the document. Eg. "standard" is not defined in the document
2. This is a bug

Ping @opoudjis about this behavior.

**Comment by Intelligent2013** [comment]
> The term referenced is not present in the document. Eg. "standard" is not defined in the document

'standard` is defined in the document:

```adoc
[[sec_3]]
== Terms and definitions

[.boilerplate]
=== Override

For the purposes of this British {{standard,Standard}}, the following terms and definitions apply.
...
=== standard

document, established by consensus and approved by a recognized body, that provides for common and repeated use, rules, guidelines or characteristics for activities or their results, aimed at the achievement of the optimum degree of order in a given context

```
and metanorma xml contains reference ` <em>Standard</em> (<xref target="term-standard"><strong>3.26</strong></xref>)` and Terms section:
```
<terms id="sec_3" obligation="normative" displayorder="7"><title depth="1">3<tab/>Terms and definitions</title>

<p id="_...">For the purposes of this British <em>Standard</em> (<xref target="term-standard"><strong>3.26</strong></xref>), the following terms and definitions apply.</p>
```

**Comment by ronaldtse** [comment]
Okay, so this is a Metanorma implementation issue -- the term rendering is wrong -- it should not show the italics and content within parentheses outside of the Terms and definition clause. There is a ticket for this filed already, and @opoudjis needs to be aware of this gap here. 

Thanks for investigating this issue.

**Comment by opoudjis** [comment]
That behaviour (no italics and xref outside of terms & definitions, italics and xref only in the first instance in terms & definitions) is already implemented in ISO, and BSI inherits ISO behaviour. The example here *is* in a Terms & Definitions section, so I am not seeing what the issue is.

**Comment by ronaldtse** [comment]
@opoudjis I'm not convinced you actually saw @Intelligent2013 's snippet?
```
<p id="_...">For the purposes of this British <em>Standard</em> (<xref target="term-standard"><strong>3.26</strong></xref>), the following terms and definitions apply.</p>
```

**Comment by ronaldtse** [comment]
There is a caveat here to what you stated:

> no italics and xref outside of terms & definitions, italics and xref only in the first instance in terms & definitions

It should be:
> no italics and xref outside of "definitions", italics and xref only in the first instance in one "definition"

**Comment by opoudjis** [comment]
The issue in Metanorma has been addressed.

**Comment by Intelligent2013** [comment]
Done, term references are generated in semantic xml ok:
```xml
<clause id="sec_1" type="scope" inline-header="false" obligation="normative">
	<title>Scope</title>
	<p id="_">This British <concept>
			<refterm>standard</refterm>
			<renderterm>Standard</renderterm>
			<xref target="term-standard"/>
		</concept> specifies <concept>
			<refterm>requirement</refterm>
			<renderterm>requirements</renderterm>
			<xref target="term-requirement"/>
		</concept> for an SMS in
```
