### ISSUE TITLE
STS -> MN: Inconsistency in document structure

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#76]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

This is an interesting case, in *bs-9992* document, there is a mismatch in clauses numbers in Generated vs Original versions.

This is how part the table of contents of *bs-9992* looks like:
Generated:
![issue3-generated](https://user-images.githubusercontent.com/33627611/135788525-083033b0-5e7e-4c40-a35e-2977b12eb082.PNG)

Original:
![issue3-original](https://user-images.githubusercontent.com/33627611/135788538-9210194a-9ea9-4b1d-83e4-0372a320462a.PNG)

Note that *Scope*, *Normative references*, *Terms and definitions*, etc, are shown (encoded) as sub-clauses instead of clauses. Leading to unwanted results in the whole document. This inconsistency is introduced by *Section 1: General* and subsequent titles.

@ronaldtse, I draw your attention to this case to determine what to do here.
This is like a new section structure that may require additional markup.

Thanks!

**Comment by Intelligent2013** [comment]
Source STS XML has such structure with nested elements inside `sec` with the title `Section x`:
```xml
<body>
		<sec id="section_1">
			<title>Section 1: General</title>
			<sec id="sec_0">
				<label>0</label>
				<title>Introduction</title>
				...
			<sec id="sec_1" sec-type="scope">
				<label>1</label>
				<title>Scope</title>
				...
			<sec id="sec_2" sec-type="norm-refs">
				<label>2</label>
				<title>Normative references</title>
				...
			<sec id="sec_3" sec-type="terms">
				<label>3</label>
				<title>Terms and definitions</title>
				...
			<sec id="sec_4">
				<label>4</label>
				<title>General recommendations and background</title>
				...
		<sec id="section_2">
			<title>Section 2: Management of fire risk</title>
			<sec id="sec_5">
				<label>5</label>
				<title>General management procedures</title>
				...
			<sec id="sec_6">
				<label>6</label>
				<title>Fire risk assessment</title>
				...
			<sec id="sec_7">
				<label>7</label>
				<title>Emergency planning</title>
				...			
```

It seems I have to encode xml that contains `sec` with `id` starts with `section_` and `title` starts with `Section ` to:
- create ToC (similar to BIPM Appendix 1 ToC) with `Section X`
- don't put `<sec id="section_x"` into adoc
- in mn->sts conversion, create xml hierarchy based on metanorma xml `<toc>` elements

**Comment by Intelligent2013** [comment]
No, my proposal isn't workable. Besides Section's titles, there are  commentaries and notes under titles:
![image](https://user-images.githubusercontent.com/5559926/136441963-f344744a-32b4-473b-a02c-4261da0b79d9.png)
. . .
![image](https://user-images.githubusercontent.com/5559926/136441999-a23568be-7c0f-4bde-afba-adfb33168af1.png)

**Comment by manuel489** [comment]
*BS 9999* standard also suffers of this issue.

**Comment by Intelligent2013** [comment]
This issue depends on https://github.com/metanorma/metanorma-bsi/issues/97.

**Comment by Intelligent2013** [comment]
Issue fixed:
![image](https://user-images.githubusercontent.com/5559926/158032942-2e6e7454-b276-45e4-b171-1dfa12abf964.png)


> BS 9999 standard also suffers of this issue.

Fixed:
![image](https://user-images.githubusercontent.com/5559926/158032922-8750deba-2a18-4738-8e0c-c935efd29d2c.png)
