### ISSUE TITLE
STS->MN: paragraphs inside footnote

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#81]
Source: https://github.com/metanorma/mn-samples-bsi/issues/60, https://github.com/metanorma/mn-samples-bsi/issues/61

Source STS sample:
```xml
<fn id="fn_1">
	<label>
		<sup>1</sup>
	</label>
	<p>GHTF/SG3/N19:2012 – Nonconformity Grading System for Regulatory Purposes and Information Exchange</p>
	<p>
		<uri>http://www.imdrf.org/docs/ghtf/final/sg3/technical-docs/ghtf-sg3-n19-2012-nonconformity-grading-121102.doc</uri>
	</p>
</fn>
```

Current adoc:
```adoc
footnote:[GHTF/SG3/N19:2012 – Nonconformity Grading System for Regulatory Purposes and Information Exchangehttp://www.imdrf.org/docs/ghtf/final/sg3/technical
```

**Comment by ronaldtse** [comment]
So a footnote in Metanorma Adoc needs to support a block syntax.

**Comment by Intelligent2013** [comment]
To do:
from: https://www.metanorma.org/author/topics/document-format/text/#footnotes

> Multi-paragraph footnotes can be entered using the macro footnoteblock:[id] [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.6.4], where id is the identifier of a note containing the contents of the footnote:


```adoc
This is a paragraph.footnoteblock:[id] This continues the paragraph.

[[id]]
[NOTE]
--
This is

a multi-paragraph

footnote
--
```
