### ISSUE TITLE
STS -> MN: Add label for "Scope" section

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mnconvert#84]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

It seems that *Scope* section is not getting any label for cross-references.

From *isoiec-29151*:
````
== Scope

This Recommendation | International Standard establishes...
````

Should be:
````
[[sec_1]]
== Scope

This Recommendation | International Standard establishes...
````

**Comment by manuel489** [comment]
Confirmed. Closing.
