### ISSUE TITLE
Enable mnconvert to generate NISO STS (and confirm compliant with IEC format)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#95]
https://github.com/metanorma/metanorma-iec/issues/111

**Comment by Intelligent2013** [comment]
mnconvert updated and v.1.13.0 released: https://github.com/metanorma/mnconvert/releases/tag/v1.13.0
Example of resulted NISO STS xml: 
[iec-60050-192.sts.niso.zip](https://github.com/metanorma/mnconvert/files/7546245/iec-60050-192.sts.niso.zip)

**Comment by ronaldtse** [comment]
We also need to confirm that the NISO STS generated is conformant to IEC style. They have provided their STS documents here: https://github.com/metanorma/mn-samples-iec-private.

@Intelligent2013 can you help confirm the generated output? Thanks.

**Comment by Intelligent2013** [comment]
Regarding `<editing-instruction>`, there are 3 kind in (`iec63159-2-2{ed1.0}en.xml):
- Addition
```xml
<editing-instruction>
<p id="p-25">
<italic>Addition:</italic>
</p>
</editing-instruction>
```
- Replacement
```xml
<editing-instruction>
<p id="p-35">
<italic>Replacement:</italic>
</p>
```
- Modification
```xml
<editing-instruction>
<p id="p-48">
<italic>Modification:</italic>
</p>
</editing-instruction>
```

In the metanorma (https://www.metanorma.org/author/topics/document-format/changes/) there are:
- add
- modify (If the `change` attribute has the value `modify`, the replacement text needs to be provided.)
- delete

I.e. mapping table between Metanorma and STS XML is:
- add -> Addition
- modify  -> Replacement
- delete -> ?
- ? -> Modification

**Comment by Intelligent2013** [comment]
@ronaldtse  resulted STS NISO examples: [IEC.NISO.STS.zip](https://github.com/metanorma/mnconvert/files/7557912/IEC.NISO.STS.zip)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

Ping @opoudjis re: https://github.com/metanorma/mnconvert/issues/95#issuecomment-971995418

**Comment by ronaldtse** [comment]
@Intelligent2013 is this done? Then we can close it, thanks.

**Comment by Intelligent2013** [comment]
Done.

**Comment by ronaldtse** [comment]
Thanks!
