### ISSUE TITLE
Do not fail if image not found

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#99]
e.g.
https://github.com/metanorma/mn-samples-bsi/runs/4234346817?check_suite_focus=true

```
Transforming...
Can't copy file: java.nio.file.NoSuchFileException: /home/runner/work/mn-samples-bsi/mn-samples-bsi/reference-docs/adoptions/bs-en-iso-13485-2012/images/fig_1.png
End!
rm -rf sources.mnconvert/adoptions/isoiec-29151/ && \
java -jar mnconvert/target/mnconvert-1.13.0.jar --output "sources.mnconvert/adoptions/isoiec-29151/document.adoc" "reference-docs/adoptions/isoiec-29151/30286827.xml"
mnconvert 
```

We still want the transformed content without the image, even though an error message is to be displayed.

**Comment by Intelligent2013** [comment]
@ronaldtse  the message `Can't copy file: java.nio.file.NoSuchFileException:...` is just a warning:
```java
} catch (IOException ex) {
            logger.warning("Can't copy file: " + ex.toString());
        }
```
and it didn't interrupt the process.

The command `rm...` is preliminary step for processing :
```
rm -rf sources.mnconvert/adoptions/isoiec-29151/ && \
java -jar mnconvert/target/mnconvert-1.13.0.jar --output "sources.mnconvert/adoptions/isoiec-29151/document.adoc" "reference-docs/adoptions/isoiec-29151/30286827.xml"
```
and relates to the next document in batch processing (for `isoiec-29151`, not `bs-en-iso-13485-2012`).

The resulted adocs created here successfully:
https://github.com/metanorma/mn-samples-bsi/tree/main/sources.mnconvert/adoptions/bs-en-iso-13485-2012

**Comment by ronaldtse** [comment]
Confirmed, it works.
